#!/usr/bin/env bash
# edc-clean-slate: detect v1 / partial-v2 artifacts and wipe .context/ for a fresh v2 build.
#
# Modes:
#   --check       exit 0 if .context/ is clean v2 or empty; exit 10 if v1/partial leftovers exist; exit 11 if .context/ valid v2.
#   --force       unconditionally wipe .context/ (and AGENTS.md if present).
#   (default)     wipe only if v1/partial leftovers detected; preserve a healthy v2 layout.
#
# v1 indicators (any of):
#   .context/.meta.json
#   .context/context.md
#   .context/full-context.md  (v1 placed it at top level; v2 puts it under build/)
#   .context/issues.md        (v1 placed it at top level; v2 puts it under reports/)
#   .context/complexity.md    (v1 top-level; v2 under reports/)
#   any other top-level *.md file in .context/ besides index.md
#
# Partial-v2 indicators (any of):
#   .context/ exists but .context/manifest.json missing
#   .context/manifest.json exists but doesn't parse, or schemaVersion != 2
#
# Exit codes:
#   0   action taken (wiped) or nothing-to-do
#   10  --check: leftovers present (caller should treat as "needs full rebuild")
#   11  --check: layout is healthy v2
#   2   bash version too low / setup error
[[ "${BASH_VERSINFO[0]:-0}" -ge 4 ]] || {
  echo "edc-clean-slate: requires bash >= 4.0" >&2
  exit 2
}

set -uo pipefail

CTX=".context"
MANIFEST="$CTX/manifest.json"
AGENTS="AGENTS.md"

mode="auto"
case "${1:-}" in
  --check) mode="check" ;;
  --force) mode="force" ;;
  "")      mode="auto" ;;
  *) echo "usage: edc-clean-slate.sh [--check|--force]" >&2; exit 2 ;;
esac

has_v1_leftovers() {
  [ -d "$CTX" ] || return 1
  [ -f "$CTX/.meta.json" ] && return 0
  [ -f "$CTX/context.md" ] && return 0
  [ -f "$CTX/full-context.md" ] && return 0
  [ -f "$CTX/issues.md" ] && return 0
  [ -f "$CTX/complexity.md" ] && return 0
  # any top-level .md other than index.md
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    case "$(basename "$f")" in
      index.md) ;;
      *) return 0 ;;
    esac
  done < <(find "$CTX" -maxdepth 1 -name '*.md' -type f 2>/dev/null)
  return 1
}

has_partial_v2() {
  [ -d "$CTX" ] || return 1
  if [ ! -f "$MANIFEST" ]; then
    # .context/ exists but no manifest → partial
    if find "$CTX" -mindepth 1 -print -quit 2>/dev/null | grep -q .; then
      return 0
    fi
    return 1
  fi
  if command -v jq >/dev/null 2>&1; then
    jq -e '.schemaVersion == 2' "$MANIFEST" >/dev/null 2>&1 || return 0
  fi
  return 1
}

is_healthy_v2() {
  [ -f "$MANIFEST" ] || return 1
  command -v jq >/dev/null 2>&1 || return 1
  jq -e '.schemaVersion == 2' "$MANIFEST" >/dev/null 2>&1 || return 1
  ! has_v1_leftovers
}

wipe() {
  rm -rf "$CTX"
  # AGENTS.md is regenerated by every full build; safe to remove so a stale one
  # can't claim the runtime mode is something it isn't.
  [ -f "$AGENTS" ] && rm -f "$AGENTS"
  echo "edc-clean-slate: wiped $CTX/ and $AGENTS"
}

case "$mode" in
  check)
    if [ ! -d "$CTX" ]; then
      # no context dir = clean enough for a full build
      exit 11
    fi
    if has_v1_leftovers; then
      echo "edc-clean-slate: v1 leftovers detected" >&2
      exit 10
    fi
    if has_partial_v2; then
      echo "edc-clean-slate: partial v2 build detected" >&2
      exit 10
    fi
    if is_healthy_v2; then
      exit 11
    fi
    # exists but no recognizable signal — treat as partial
    exit 10
    ;;
  force)
    wipe
    exit 0
    ;;
  auto)
    if has_v1_leftovers; then
      echo "edc-clean-slate: v1 leftovers — wiping for fresh v2 build" >&2
      wipe
      exit 0
    fi
    if has_partial_v2; then
      echo "edc-clean-slate: partial v2 build — wiping for fresh v2 build" >&2
      wipe
      exit 0
    fi
    # nothing to do
    exit 0
    ;;
esac
