#!/usr/bin/env bash
# Task 11 smoke test: end-to-end audit orchestrator with mocked agent.
#
# Exercises the same patterns as t6 (mocked claude, hermetic git env) but for
# the audit pipeline:
#
#   - missing context → orchestrator runs build recovery, then audit
#   - stale context  → orchestrator runs update recovery, then audit
#   - one audit worker runs per manifest module, then synthesis writes both reports
#   - synthesis writes only one report → orchestrator exits non-zero
#   - synthesis writes structureless report → orchestrator exits non-zero
#
# Run from repo root: bash tests/hardening/t11-audit-orchestrator.sh
set -euo pipefail


ORIG_DIR="$(pwd)"
SCRIPT="$ORIG_DIR/plugins/edc/scripts/edc-audit.sh"
TMPDIR_T11=$(mktemp -d)
MOCK_BIN="$TMPDIR_T11/bin"
trap 'rm -rf "$TMPDIR_T11"' EXIT

echo "=== T11: audit orchestrator (mocked agent) ==="

# ── build the mock claude ────────────────────────────────────────────────────
#
# The mock writes whichever artifacts the prompt asks for. A "scenario file"
# at $TMPDIR_T11/scenario controls synthesis output (valid|missing-issues|stub).
mkdir -p "$MOCK_BIN"
cat > "$MOCK_BIN/claude" <<MOCK
#!/usr/bin/env bash
set -euo pipefail
prompt=\$(cat)
SCENARIO_FILE="$TMPDIR_T11/scenario"
LOG_FILE="$TMPDIR_T11/audit-log"
scenario="valid"
[ -f "\$SCENARIO_FILE" ] && scenario=\$(cat "\$SCENARIO_FILE")

if [[ "\$prompt" == *"AUDIT WORKER TASK"* ]]; then
  module=\$(printf '%s\n' "\$prompt" | grep '^AUDIT_MODULE: ' | head -1 | sed 's/^AUDIT_MODULE: //')
  report_path=\$(printf '%s\n' "\$prompt" | grep '^AUDIT_REPORT_PATH: ' | head -1 | sed 's/^AUDIT_REPORT_PATH: //')
  mkdir -p "\$(dirname "\$report_path")"
  printf 'worker:%s\n' "\$module" >> "\$LOG_FILE"
  printf '## Module Audit: %s\n\nScoped finding.\n' "\$module" > "\$report_path"
  exit 0
fi

if [[ "\$prompt" == *"AUDIT SYNTHESIS TASK"* ]]; then
  printf 'synthesis\n' >> "\$LOG_FILE"
  mkdir -p edc-context/reports
  case "\$scenario" in
    valid)
      printf '## Summary\n\nSynthesized findings.\n' > edc-context/reports/complexity.md
      printf '## Known Issues\n\nSynthesized findings.\n' > edc-context/reports/issues.md
      ;;
    missing-issues)
      printf '## Summary\n\nSynthesized findings.\n' > edc-context/reports/complexity.md
      # deliberately do NOT write issues.md
      ;;
    stub-complexity)
      printf 'no headings here just plain text\n' > edc-context/reports/complexity.md
      printf '## Known Issues\n\nSynthesized findings.\n' > edc-context/reports/issues.md
      ;;
  esac
  exit 0
fi

if [[ "\$prompt" == *"name: edc-audit"* ]]; then
  printf 'single\n' >> "\$LOG_FILE"
  mkdir -p edc-context/reports
  printf '## Summary\n\nLegacy single-pass findings.\n' > edc-context/reports/complexity.md
  printf '## Known Issues\n\nLegacy single-pass findings.\n' > edc-context/reports/issues.md
  exit 0
fi

if [[ "\$prompt" == *"name: edc-update-impl"* ]] || [[ "\$prompt" == *"# Update Context"* ]]; then
  head=\$(git rev-parse HEAD)
  sed -i.bak 's/"sourceCommit":"[^"]*"/"sourceCommit":"'"\$head"'"/' edc-context/manifest.json
  rm -f edc-context/manifest.json.bak
  exit 0
fi

if [[ "\$prompt" == *"edc-build"* ]]; then
  mkdir -p edc-context/modules edc-context/reports
  printf '<!-- generated by t11 mock -->\n# Stub\n\n## Module Map\n\n- root\n- lib\n' > edc-context/index.md
  head=\$(git rev-parse HEAD)
  printf '{"schemaVersion":2,"sourceCommit":"%s","modules":[{"name":"root","doc":"edc-context/modules/root.md"},{"name":"lib","doc":"edc-context/modules/lib.md"}]}\n' "\$head" > edc-context/manifest.json
  printf '<!-- generated by t11 mock -->\n# root\n\n## Files\n\n- src.py\n' > edc-context/modules/root.md
  printf '<!-- generated by t11 mock -->\n# lib\n\n## Files\n\n- lib.py\n' > edc-context/modules/lib.md
  exit 0
fi

echo "MOCK ERROR: unrecognized prompt: \$prompt" >&2
exit 1
MOCK
chmod +x "$MOCK_BIN/claude"

# ── helper: set up a minimal git repo + optionally pre-existing context ──────
setup_repo() {
  local with_context="$1"
  rm -rf "$TMPDIR_T11/repo"
  rm -f "$TMPDIR_T11/audit-log"
  mkdir -p "$TMPDIR_T11/repo"
  cd "$TMPDIR_T11/repo"
  export GIT_CONFIG_GLOBAL=/dev/null
  export GIT_CONFIG_SYSTEM=/dev/null
  git init -q
  git config user.email "t@t.com"
  git config user.name "T"
  git config commit.gpgsign false
  echo "src" > src.py
  echo "lib" > lib.py
  git add src.py lib.py
  git commit -q -m "init"
  mkdir -p .edc/skills/edc-build-impl .edc/skills/edc-update-impl .edc/skills/edc-audit/references
  printf '# Build Context\nedc-build\n' > .edc/skills/edc-build-impl/SKILL.md
  printf '# Update Context\nedc-update\n' > .edc/skills/edc-update-impl/SKILL.md
  printf '# Audit Code Quality\nname: edc-audit\n' > .edc/skills/edc-audit/SKILL.md
  printf '# Scope and Standards\n' > .edc/skills/edc-audit/references/scope-and-standards.md
  printf '# Smell Baseline\n' > .edc/skills/edc-audit/references/smell-baseline.md
  printf '# Quality Checks\n' > .edc/skills/edc-audit/references/quality-checks.md
  printf '# Reporting\n' > .edc/skills/edc-audit/references/reporting.md
  if [ "$with_context" = "fresh" ]; then
    mkdir -p edc-context/modules
    head=$(git rev-parse HEAD)
    printf '<!-- t11 -->\n# Stub\n\n## Module Map\n\n- root\n- lib\n' > edc-context/index.md
    printf '{"schemaVersion":2,"sourceCommit":"%s","modules":[{"name":"root","doc":"edc-context/modules/root.md"},{"name":"lib","doc":"edc-context/modules/lib.md"}]}\n' "$head" > edc-context/manifest.json
    printf '<!-- t11 -->\n# root\n\n## Files\n\n- src.py\n' > edc-context/modules/root.md
    printf '<!-- t11 -->\n# lib\n\n## Files\n\n- lib.py\n' > edc-context/modules/lib.md
  elif [ "$with_context" = "stale" ]; then
    mkdir -p edc-context/modules
    printf '<!-- t11 -->\n# Stub\n\n## Module Map\n\n- root\n- lib\n' > edc-context/index.md
    printf '{"schemaVersion":2,"sourceCommit":"deadbeef","modules":[{"name":"root","doc":"edc-context/modules/root.md"},{"name":"lib","doc":"edc-context/modules/lib.md"}]}\n' > edc-context/manifest.json
    printf '<!-- t11 -->\n# root\n\n## Files\n\n- src.py\n' > edc-context/modules/root.md
    printf '<!-- t11 -->\n# lib\n\n## Files\n\n- lib.py\n' > edc-context/modules/lib.md
  fi
}

export PATH="$MOCK_BIN:$PATH"
export EDC_AGENT_CLI=claude

# Sanity check.
which_claude=$(command -v claude)
[ "$which_claude" = "$MOCK_BIN/claude" ] || { echo "FAIL: mock not on PATH (got $which_claude)"; exit 1; }

# ── 11a: missing context → build recovery → audit succeeds ──────────────────
setup_repo "none"
echo "valid" > "$TMPDIR_T11/scenario"
result=0
out=$(/bin/bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -eq 0 ] && [ -f edc-context/reports/complexity.md ] && [ -f edc-context/reports/issues.md ] \
   && [ "$(grep -c '^worker:' "$TMPDIR_T11/audit-log" 2>/dev/null || true)" -eq 2 ] \
   && grep -q '^synthesis$' "$TMPDIR_T11/audit-log" \
   && node -e 'const j=require("./edc-context/build/last-run.json"); process.exit(j.kind === "audit" && j.exitCode === 0 && j.reasonCode === "success" ? 0 : 1)'; then
  echo "PASS: missing-context recovery → per-module audit + synthesis produced both reports"
else
  echo "FAIL (11a): missing-context path. exit=$result"
  echo "--- output ---"; echo "$out"; echo "--- end ---"
  exit 1
fi

# ── 11b: stale context → update recovery → audit succeeds ───────────────────
setup_repo "stale"
echo "valid" > "$TMPDIR_T11/scenario"
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -eq 0 ] && [ -f edc-context/reports/complexity.md ] && [ -f edc-context/reports/issues.md ] \
   && [ "$(grep -c '^worker:' "$TMPDIR_T11/audit-log" 2>/dev/null || true)" -eq 2 ] \
   && grep -q '^synthesis$' "$TMPDIR_T11/audit-log"; then
  echo "PASS: stale-context recovery → per-module audit + synthesis produced both reports"
else
  echo "FAIL (11b): stale-context path. exit=$result"
  echo "--- output ---"; echo "$out"; echo "--- end ---"
  exit 1
fi

# ── 11c: fresh context, audit subprocess skips issues.md → orchestrator fails ─
setup_repo "fresh"
echo "missing-issues" > "$TMPDIR_T11/scenario"
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -ne 0 ] && echo "$out" | grep -q "audit report missing" \
   && node -e 'const j=require("./edc-context/build/last-run.json"); process.exit(j.kind === "audit" && j.exitCode === 1 && j.reasonCode === "audit-report-validation" ? 0 : 1)'; then
  echo "PASS: missing report rejected with descriptive error"
else
  echo "FAIL (11c): expected non-zero exit + 'audit report missing'. exit=$result"
  echo "--- output ---"; echo "$out"; echo "--- end ---"
  exit 1
fi

# ── 11d: fresh context, audit subprocess writes structureless report → fails ─
setup_repo "fresh"
echo "stub-complexity" > "$TMPDIR_T11/scenario"
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -ne 0 ] && echo "$out" | grep -q "no '## ' headings"; then
  echo "PASS: structureless report rejected with descriptive error"
else
  echo "FAIL (11d): expected non-zero exit + 'no ## headings' error. exit=$result"
  echo "--- output ---"; echo "$out"; echo "--- end ---"
  exit 1
fi

cd "$ORIG_DIR"
echo ""
echo "All T11 checks passed."
