#!/usr/bin/env bash
# Task 13 smoke test: end-to-end update orchestrator preflight + spawn.
#
# Pins the contract that scripts/edc-update.sh:
#   - REFUSES to act when no edc-context/ exists (tells user to run build)
#   - REFUSES on partial / malformed v2 (tells user to run --force build)
#   - REFUSES on v1 layout with the migration hint
#   - PROCEEDS on healthy v2 → spawns update subprocess → doctor validates
#   - derives update lineage solely from manifest.sourceCommit
#   - refuses missing or invalid provenance without spawning or mutating context
#   - rejects review-only --base rather than overloading it as update lineage
#
# Run from repo root: bash tests/hardening/t13-update-orchestrator.sh
set -euo pipefail


ORIG_DIR="$(pwd)"
SCRIPT="$ORIG_DIR/plugins/edc/scripts/edc-update.sh"
TMPDIR_T13=$(mktemp -d)
MOCK_BIN="$TMPDIR_T13/bin"
trap 'rm -rf "$TMPDIR_T13"' EXIT

echo "=== T13: update orchestrator (mocked agent) ==="

mkdir -p "$MOCK_BIN"
cat > "$MOCK_BIN/claude" <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
prompt=$(cat)
LOG="${EDC_T13_LOG:?}"
echo "spawned: $(echo "$prompt" | head -1)" >> "$LOG"

if [[ "$prompt" == *"name: edc-update-impl"* ]] || [[ "$prompt" == *"# Update Context"* ]]; then
  echo "$prompt" > "$EDC_T13_LOG.prompt"
  head=$(git rev-parse HEAD)
  sed -i.bak 's/"sourceCommit":"[^"]*"/"sourceCommit":"'"$head"'"/' edc-context/manifest.json
  rm -f edc-context/manifest.json.bak
  exit 0
fi

if [[ "$prompt" == *"name: edc-context-curator-edit-impl"* ]]; then
  echo "curator-edit" >> "$LOG"
  exit 0
fi

if [[ "$prompt" == *"edc-context-curator-impl"* ]] || [[ "$prompt" == *"Context Curator"* ]]; then
  echo "curator" >> "$LOG"
  mkdir -p edc-context/reports
  printf '# Context Curation Report\n\n## Summary\n- t13 curator\n' > edc-context/reports/context-curation.md
  exit 0
fi

if [[ "$prompt" == *"name: edc-build-impl"* ]] || [[ "$prompt" == *"# Build Context"* ]]; then
  # Should never happen in T13 — update orchestrator must not spawn build.
  echo "MOCK ERROR: update orchestrator spawned a build" >&2
  exit 1
fi

echo "MOCK ERROR: unrecognized prompt: $prompt" >&2
exit 1
MOCK
chmod +x "$MOCK_BIN/claude"

setup_repo() {
  rm -rf "$TMPDIR_T13/repo"
  mkdir -p "$TMPDIR_T13/repo/src"
  cd "$TMPDIR_T13/repo"
  export GIT_CONFIG_GLOBAL=/dev/null
  export GIT_CONFIG_SYSTEM=/dev/null
  git init -q -b main
  git config user.email "t@t.com"
  git config user.name "T"
  git config commit.gpgsign false
  echo "src" > src/main.py
  git add src/main.py
  git commit -q -m "init"
  echo "" > "$TMPDIR_T13/log"
}

write_healthy_v2() {
  mkdir -p edc-context/modules edc-context/reports edc-context/build
  local commit_hash="${1:-}"
  if [ -z "$commit_hash" ]; then
    commit_hash=$(git rev-parse HEAD)
  fi
  cat > edc-context/manifest.json <<EOF
{"schemaVersion":2,"sourceCommit":"$commit_hash","modules":[{"name":"root","doc":"edc-context/modules/root.md","match":{"prefixes":["src/"]}}],"unmapped":{"allowedGlobs":["*"]},"policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"repoContextFile":"edc-context/index.md","reports":{"issues":"edc-context/reports/issues.md","complexity":"edc-context/reports/complexity.md"},"build":{"buildInfoFile":"edc-context/build/build.json"},"coverage":{"mappedFileCount":0,"unmappedFileCount":0,"ambiguousPathCount":0}}
EOF
  printf '<!-- t13 -->\n# Stub\n\n## Module Map\n\n- root\n' > edc-context/index.md
  printf '<!-- t13 -->\n# root\n\n## Files\n\n- src.py\n' > edc-context/modules/root.md
  printf '## Known Issues\n' > edc-context/reports/issues.md
  printf '## Summary\n' > edc-context/reports/complexity.md
  printf '{}' > edc-context/build/build.json
  printf '# Agent Instructions\n\nThis repo ships deep architectural context generated by EDC.\n\nSee [`edc-context/index.md`](edc-context/index.md).\nSee [`edc-context/manifest.json`](edc-context/manifest.json).\n' > AGENTS.md
}

export PATH="$MOCK_BIN:$PATH"
export EDC_AGENT_CLI=claude
export EDC_T13_LOG="$TMPDIR_T13/log"

# ── 13a: no edc-context/ → REFUSE with "run edc-build" hint ────────────────────
setup_repo
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -eq 0 ]; then
  echo "FAIL (13a): expected non-zero exit on missing edc-context/"
  echo "$out"; exit 1
fi
if echo "$out" | grep -q "no edc-context/" && echo "$out" | grep -q "edc-build"; then
  echo "PASS: no edc-context/ refused with build hint"
else
  echo "FAIL (13a): expected refusal mentioning 'no edc-context/' and 'edc-build'"
  echo "$out"; exit 1
fi
if grep -q "spawned" "$EDC_T13_LOG"; then
  echo "FAIL (13a): agent was spawned despite refusal"
  cat "$EDC_T13_LOG"; exit 1
fi

# ── 13b: partial v2 (no manifest) → REFUSE with --force hint ─────────────────
setup_repo
mkdir -p edc-context/modules
printf '# stub\n' > edc-context/modules/foo.md
echo "" > "$EDC_T13_LOG"
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -eq 0 ]; then
  echo "FAIL (13b): expected non-zero exit on partial v2"
  echo "$out"; exit 1
fi
if echo "$out" | grep -q "partial or malformed" && echo "$out" | grep -q "force"; then
  echo "PASS: partial v2 refused with --force hint"
else
  echo "FAIL (13b): expected refusal mentioning partial/malformed and --force"
  echo "$out"; exit 1
fi
if grep -q "spawned" "$EDC_T13_LOG"; then
  echo "FAIL (13b): agent was spawned despite refusal"
  cat "$EDC_T13_LOG"; exit 1
fi

# ── 13c: v1 layout → REFUSE with migration hint ─────────────────────────────
setup_repo
mkdir -p edc-context
printf '{}' > edc-context/.meta.json
echo "" > "$EDC_T13_LOG"
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -eq 0 ]; then
  echo "FAIL (13c): expected non-zero exit on v1 layout"
  echo "$out"; exit 1
fi
if echo "$out" | grep -q "legacy v1" && echo "$out" | grep -q "rm -rf edc-context" \
  && node -e 'const j=require("./edc-context/build/last-run.json"); process.exit(j.kind === "update" && j.exitCode === 1 && j.reasonCode === "legacy-v1-layout" ? 0 : 1)'; then
  echo "PASS: v1 layout refused with migration hint"
else
  echo "FAIL (13c): expected migration hint"
  echo "$out"; exit 1
fi
if grep -q "spawned" "$EDC_T13_LOG"; then
  echo "FAIL (13c): agent was spawned despite refusal"
  cat "$EDC_T13_LOG"; exit 1
fi

# ── 13d: healthy v2 → update from manifest lineage ───────────────────────────
setup_repo
lineage_source=$(git rev-parse HEAD)
write_healthy_v2 "$lineage_source"
echo "more" > src/extra.py && git add src/extra.py && git commit -q -m "more"
echo "" > "$EDC_T13_LOG"
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -ne 0 ]; then
  echo "FAIL (13d): orchestrator exited $result on healthy v2"
  echo "$out"; exit 1
fi
if grep -q "spawned" "$EDC_T13_LOG" \
  && grep -Fqx "CLI ARGUMENTS: --context-source $lineage_source" "$EDC_T13_LOG.prompt" \
  && node -e 'const j=require("./edc-context/build/last-run.json"); process.exit(j.kind === "update" && j.exitCode === 0 && j.reasonCode === "success" && Array.isArray(j.outputs) && j.outputs.includes("edc-context/manifest.json") && Array.isArray(j.checks) && j.checks.some(c => c.name === "edc-doctor" && c.status === "success") ? 0 : 1)'; then
  echo "PASS: healthy v2 → update spawned from manifest lineage"
else
  echo "FAIL (13d): update prompt did not use manifest lineage"
  cat "$EDC_T13_LOG.prompt" 2>/dev/null || true; exit 1
fi

# ── 13e: divergent source updates from exact endpoint lineage ─────────────────
setup_repo
unrelated_tree=$(git mktree < /dev/null)
divergent_source=$(printf 'unrelated\n' | git commit-tree "$unrelated_tree")
write_healthy_v2 "$divergent_source"
echo "" > "$EDC_T13_LOG"
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -ne 0 ] || ! grep -q -- "--context-source $divergent_source" "$EDC_T13_LOG.prompt"; then
  echo "FAIL (13e): divergent context was not updated from its recorded source"
  echo "$out"; cat "$EDC_T13_LOG.prompt" 2>/dev/null || true; exit 1
fi
echo "PASS: divergent context updates from recorded lineage"

# ── 13f: invalid provenance refuses without mutation or agent spawn ───────────
setup_repo
write_healthy_v2 "not-a-commit"
echo "" > "$EDC_T13_LOG"
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -ne 0 ] \
  && ! grep -q "spawned" "$EDC_T13_LOG" \
  && grep -q 'edc build --agent claude --force' <<< "$out" \
  && grep -q '"sourceCommit":"not-a-commit"' edc-context/manifest.json; then
  echo "PASS: invalid provenance refuses with explicit rebuild guidance"
else
  echo "FAIL (13f): invalid provenance spawned or mutated context"
  echo "$out"; cat "$EDC_T13_LOG"; exit 1
fi

# ── 13g: update rejects review-only --base ────────────────────────────────────
setup_repo
write_healthy_v2
echo "" > "$EDC_T13_LOG"
result=0
out=$(bash "$SCRIPT" --base main 2>&1) || result=$?
if [ "$result" -ne 0 ] \
  && ! grep -q "spawned" "$EDC_T13_LOG" \
  && grep -q 'review-only' <<< "$out"; then
  echo "PASS: update rejects review-only --base"
else
  echo "FAIL (13g): update accepted review --base"
  echo "$out"; cat "$EDC_T13_LOG"; exit 1
fi

# ── 13f: missing AGENTS.md → REFUSE as partial v2 ──────────────────────
setup_repo
write_healthy_v2
rm -f AGENTS.md
echo "" > "$EDC_T13_LOG"
result=0
out=$(bash "$SCRIPT" 2>&1) || result=$?
if [ "$result" -eq 0 ]; then
  echo "FAIL (13f): expected non-zero exit when AGENTS.md is missing"
  echo "$out"; exit 1
fi
if echo "$out" | grep -q "partial or malformed" && echo "$out" | grep -q "force"; then
  echo "PASS: missing AGENTS.md refused with --force build hint"
else
  echo "FAIL (13f): expected refusal mentioning partial/malformed and --force"
  echo "$out"; exit 1
fi
if grep -q "spawned" "$EDC_T13_LOG"; then
  echo "FAIL (13f): agent was spawned despite refusal"
  cat "$EDC_T13_LOG"; exit 1
fi

cd "$ORIG_DIR"
echo ""
echo "All T13 checks passed."
