#!/usr/bin/env bash
# t18-pi-backend: EDC_AGENT_CLI=pi uses pi CLI for spawned update/review work.
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/plugins/edc/scripts/edc-review.sh"

BASH_BIN="${BASH_BIN:-bash}"

. "$(dirname "$0")/lib/check.sh"
check_init --file
TMP="$(mktemp -d)"
LOG_DIR="$(mktemp -d)"
PI_CALLS_LOG="$LOG_DIR/pi-calls.log"
export PI_CALLS_LOG
trap 'rm -rf "$TMP" "$LOG_DIR"; check_cleanup' EXIT

setup_repo() {
  cd "$TMP"
  export GIT_CONFIG_GLOBAL=/dev/null
  export GIT_CONFIG_SYSTEM=/dev/null
  git init -q
  git config user.email test@test.com
  git config user.name Test
  git config commit.gpgsign false
  mkdir -p src
  echo 'one' > src/a.txt
  git add src/a.txt
  git commit -q -m init

  node "$ROOT/plugins/edc/hooks/lib/runtime-manifest.mjs" install "$TMP" "$ROOT/plugins/edc" >/dev/null
  mkdir -p edc-context/modules edc-context/reports
  printf '# Repo\n\n## Module Map\n' > edc-context/index.md
  printf '## Issues\n' > edc-context/reports/issues.md
  printf '## Complexity\n' > edc-context/reports/complexity.md
  printf '# Core\n\n## Files\n' > edc-context/modules/core.md
  cat > edc-context/manifest.json <<EOF
{
  "schemaVersion": 2,
  "sourceCommit": "0000000000000000000000000000000000000000",
  "policy": {"defaultMode": "advisory", "unmatchedPathPolicy": "warn-allow"},
  "modules": [
    {"name":"core", "priority": 10, "doc":"edc-context/modules/core.md", "match":{"prefixes":["src/"]}}
  ]
}
EOF
  echo 'two' > src/a.txt
  git add src/a.txt
  git commit -q -m change
}

write_mock_pi() {
  mkdir -p "$TMP/bin"
  cat > "$TMP/bin/python3" <<'MOCK_PY'
#!/usr/bin/env bash
echo "python3 should not be required for pi supervision" >&2
exit 127
MOCK_PY
  chmod +x "$TMP/bin/python3"
  cat > "$TMP/bin/pi" <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> "${PI_CALLS_LOG:-pi-calls.log}"
prompt=""
for arg in "$@"; do
  case "$arg" in
    @*) prompt="$(cat "${arg#@}")" ;;
  esac
done
write_context() {
  head=$(git rev-parse HEAD)
  mkdir -p edc-context/modules edc-context/reports
  printf '# Repo\n\n## Module Map\n' > edc-context/index.md
  printf '# Core\n\n## Files\n' > edc-context/modules/core.md
  printf '## Issues\n' > edc-context/reports/issues.md
  printf '## Complexity\n' > edc-context/reports/complexity.md
  printf '# Agent Instructions\n\nThis repo ships deep architectural context generated by EDC.\n\nSee [`edc-context/index.md`](edc-context/index.md).\nSee [`edc-context/manifest.json`](edc-context/manifest.json).\n' > AGENTS.md
  cat > edc-context/manifest.json <<EOF
{"schemaVersion":2,"sourceCommit":"$head","policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"modules":[{"name":"core","priority":10,"doc":"edc-context/modules/core.md","match":{"prefixes":["src/"]}}]}
EOF
}
finish_ok() {
  printf '{"type":"result","is_error":false,"result":"ok"}\n'
  if [ "${PI_FAKE_AGENT_END_RETRY:-0}" = "1" ]; then
    printf '{"type":"agent_end","willRetry":true,"messages":[{"role":"assistant","stopReason":"error","errorMessage":"WebSocket error","content":[{"type":"text","text":""}]}]}\n'
    printf '{"type":"auto_retry_start","attempt":1,"maxAttempts":3,"delayMs":1,"errorMessage":"WebSocket error"}\n'
    printf '{"type":"auto_retry_end","success":true,"attempt":1}\n'
    printf '{"type":"agent_end","willRetry":false,"messages":[{"role":"assistant","stopReason":"stop","content":[{"type":"text","text":"ok"}]}]}\n'
  elif [ "${PI_FAKE_AGENT_END_ERROR:-0}" = "1" ]; then
    printf '{"type":"agent_end","messages":[{"role":"assistant","stopReason":"error","errorMessage":"provider down","content":[{"type":"text","text":""}]}]}\n'
  else
    printf '{"type":"agent_end","messages":[{"role":"assistant","stopReason":"stop","content":[{"type":"text","text":"ok"}]}]}\n'
  fi
  if [ "${PI_FAKE_HANG_AFTER_AGENT_END:-0}" = "1" ]; then
    sleep 5
  fi
  exit 0
}
if [ "${PI_FAKE_AUTH_TEXT:-0}" = "1" ]; then
  printf '{"type":"session","version":3,"id":"mock","cwd":"%s"}\n' "$PWD"
  printf 'No API key found for azure-openai-responses.\n\nUse /login to log into a provider via OAuth or API key.\n'
  sleep 30
  exit 1
fi
if printf '%s' "$prompt" | grep -q 'BUILD DISCOVERY TASK'; then
  output=$(printf '%s\n' "$prompt" | grep '^DISCOVERY_OUTPUT: ' | sed 's/^DISCOVERY_OUTPUT: //')
  mkdir -p "$(dirname "$output")"
  printf '{"modules":[{"name":"core","paths":["src/"],"approxLoc":1}]}\n' > "$output"
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"discovered"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'MODULE CONTEXT TASK'; then
  output=$(printf '%s\n' "$prompt" | grep '^OUTPUT: ' | head -1 | sed 's/^OUTPUT: //')
  mkdir -p "$(dirname "$output")"
  printf '# Core\n\n## Ownership\n\nMock module.\n' > "$output"
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"module"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'CROSS-MODULE SYNTHESIS TASK'; then
  output=$(printf '%s\n' "$prompt" | grep '^OUTPUT: ' | sed 's/^OUTPUT: //')
  printf '## Flows\n\nMock.\n' > "$output"
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"cross"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'BUILD ASSEMBLY TASK'; then
  index_output=$(printf '%s\n' "$prompt" | grep '^INDEX_OUTPUT: ' | sed 's/^INDEX_OUTPUT: //')
  partial_output=$(printf '%s\n' "$prompt" | grep '^PARTIAL_MANIFEST_OUTPUT: ' | sed 's/^PARTIAL_MANIFEST_OUTPUT: //')
  build_output=$(printf '%s\n' "$prompt" | grep '^BUILD_INFO_OUTPUT: ' | sed 's/^BUILD_INFO_OUTPUT: //')
  agents_output=$(printf '%s\n' "$prompt" | grep '^AGENT_ENTRYPOINT_OUTPUT: ' | sed 's/^AGENT_ENTRYPOINT_OUTPUT: //')
  mkdir -p "$(dirname "$index_output")" "$(dirname "$build_output")" "$(dirname "$agents_output")"
  printf '# Repo\n\n## How to use\n\nRead routes.\n\n## Route by path/task\n\n- src: core\n\n## Critical global invariants\n\n- mock\n\n## Cross-module coupling / blast radius\n\n- mock\n' > "$index_output"
  printf '{"schemaVersion":2,"edcVersion":"1.1.0","repoContextFile":"edc-context/index.md","reports":{"issues":"edc-context/reports/issues.md","complexity":"edc-context/reports/complexity.md"},"build":{"buildInfoFile":"edc-context/build/build.json"},"policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"modules":[{"name":"core","doc":"edc-context/modules/core.md","summary":"mock","priority":10,"match":{"prefixes":["src/"]}}],"unmapped":{"allowedGlobs":["*"]}}\n' > "$partial_output"
  printf '{}\n' > "$build_output"
  printf '# Agent Instructions\n\nThis repo ships deep architectural context generated by EDC.\n\nSee [`edc-context/index.md`](edc-context/index.md).\nSee [`edc-context/manifest.json`](edc-context/manifest.json).\n' > "$agents_output"
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"assembled"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -Eq 'BUILD_SKILL_MARKER|name: edc-build-impl'; then
  write_context
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"built context"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -Eq 'UPDATE_SKILL_MARKER|name: edc-update-impl'; then
  write_context
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"updated context"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -Eq 'CURATOR_EDIT_SKILL_MARKER|name: edc-context-curator-edit-impl'; then
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"curator edit"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -Eq 'CURATOR_SKILL_MARKER|name: edc-context-curator-impl'; then
  mkdir -p edc-context/reports
  printf '# Context Curation Report\n\n## Summary\n- mock pi curator\n' > edc-context/reports/context-curation.md
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"curated"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -Eq 'REVIEW_SKILL_MARKER|name: edc-review'; then
  task_path=$(printf '%s' "$prompt" | grep -oE 'TASK FILE: [^ ]+' | head -1 | awk '{print $3}')
  report_path="$(dirname "$task_path")/report-$(basename "$task_path" .md).md"
  mkdir -p "$(dirname "$report_path")"
  printf '## Findings\n\nmock pi review\n' > "$report_path"
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"reviewed"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'AUDIT WORKER TASK'; then
  report_path=$(printf '%s\n' "$prompt" | grep '^AUDIT_REPORT_PATH: ' | head -1 | sed 's/^AUDIT_REPORT_PATH: //')
  mkdir -p "$(dirname "$report_path")"
  printf '## Module Audit\n\nmock pi module audit\n' > "$report_path"
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"audited module"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'AUDIT SYNTHESIS TASK'; then
  complexity_path=$(printf '%s\n' "$prompt" | grep '^CANONICAL_COMPLEXITY_REPORT: ' | head -1 | sed 's/^CANONICAL_COMPLEXITY_REPORT: //')
  issues_path=$(printf '%s\n' "$prompt" | grep '^CANONICAL_ISSUES_REPORT: ' | head -1 | sed 's/^CANONICAL_ISSUES_REPORT: //')
  mkdir -p "$(dirname "$complexity_path")" "$(dirname "$issues_path")"
  printf '## Complexity\n\nmock pi audit\n' > "$complexity_path"
  printf '## Issues\n\nmock pi audit\n' > "$issues_path"
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"audited"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -Eq 'AUDIT_SKILL_MARKER|name: edc-audit'; then
  mkdir -p edc-context/reports
  printf '## Complexity\n\nmock pi audit\n' > edc-context/reports/complexity.md
  printf '## Issues\n\nmock pi audit\n' > edc-context/reports/issues.md
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"audited"}}\n'
  finish_ok
fi
printf '{"type":"result","is_error":true,"result":"unexpected prompt"}\n'
exit 1
MOCK
  chmod +x "$TMP/bin/pi"
}

setup_repo
write_mock_pi
PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_KEEP_REVIEW_TASKS=1 "$BASH_BIN" "$SCRIPT" HEAD --base HEAD~1 --committed-only >"$LOG_DIR/out.log" 2>"$LOG_DIR/err.log"
rc=$?

if [ "$rc" -eq 0 ] && [ -f review-HEAD.md ] && grep -q 'mock pi review' review-HEAD.md; then
  check "18.1: EDC_AGENT_CLI=pi completes stale-context review via pi CLI" 1
else
  check "18.1: EDC_AGENT_CLI=pi completes stale-context review via pi CLI" 0
  cat "$LOG_DIR/out.log" "$LOG_DIR/err.log"
fi

if [ -f "$PI_CALLS_LOG" ] && grep -q -- '--mode json' "$PI_CALLS_LOG" && grep -q -- '--no-context-files' "$PI_CALLS_LOG"; then
  check "18.2: pi backend uses json clean-slate CLI mode" 1
else
  check "18.2: pi backend uses json clean-slate CLI mode" 0
  cat "$PI_CALLS_LOG" 2>/dev/null || true
fi

if [ -f "$PI_CALLS_LOG" ] && grep -q -- '--no-extensions' "$PI_CALLS_LOG"; then
  check "18.2a: pi backend disables extension discovery" 1
else
  check "18.2a: pi backend disables extension discovery" 0
  cat "$PI_CALLS_LOG" 2>/dev/null || true
fi

observer_extension="$TMP/observer-extension.ts"
printf 'export default function observer() {}\n' > "$observer_extension"
extension_before=$(wc -l < "$PI_CALLS_LOG" | tr -d ' ')
PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_PI_EXTENSION_PATH="$observer_extension" "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >"$LOG_DIR/extension-update.out" 2>"$LOG_DIR/extension-update.err"
rc=$?
extension_call=$(tail -n +$((extension_before + 1)) "$PI_CALLS_LOG" | head -1)
if [ "$rc" -eq 0 ] && printf '%s\n' "$extension_call" | grep -Fq -- "--no-extensions -e $observer_extension"; then
  check "18.2b: pi backend loads only the explicit extension" 1
else
  check "18.2b: pi backend loads only the explicit extension" 0
  cat "$LOG_DIR/extension-update.out" "$LOG_DIR/extension-update.err"
  printf 'call=%s\n' "$extension_call"
fi

invalid_before=$(wc -l < "$PI_CALLS_LOG" | tr -d ' ')
PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_PI_EXTENSION_PATH=relative-extension.ts "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >"$LOG_DIR/invalid-extension.out" 2>"$LOG_DIR/invalid-extension.err"
rc=$?
invalid_after=$(wc -l < "$PI_CALLS_LOG" | tr -d ' ')
if [ "$rc" -ne 0 ] && [ "$invalid_after" -eq "$invalid_before" ] && grep -q 'EDC_PI_EXTENSION_PATH must be an absolute readable file' "$LOG_DIR/invalid-extension.err"; then
  check "18.2c: pi backend rejects invalid explicit extension paths before spawn" 1
else
  check "18.2c: pi backend rejects invalid explicit extension paths before spawn" 0
  cat "$LOG_DIR/invalid-extension.out" "$LOG_DIR/invalid-extension.err"
fi

PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >"$LOG_DIR/update.out" 2>"$LOG_DIR/update.err"
rc=$?
if [ "$rc" -eq 0 ] && grep -q 'Update OK' "$LOG_DIR/update.out"; then
  check "18.3: EDC_AGENT_CLI=pi runs update orchestrator" 1
else
  check "18.3: EDC_AGENT_CLI=pi runs update orchestrator" 0
  cat "$LOG_DIR/update.out" "$LOG_DIR/update.err"
fi

PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-audit.sh" >"$LOG_DIR/audit.out" 2>"$LOG_DIR/audit.err"
rc=$?
if [ "$rc" -eq 0 ] && grep -q 'Audit reports:' "$LOG_DIR/audit.out"; then
  check "18.4: EDC_AGENT_CLI=pi runs audit orchestrator" 1
else
  check "18.4: EDC_AGENT_CLI=pi runs audit orchestrator" 0
  cat "$LOG_DIR/audit.out" "$LOG_DIR/audit.err"
fi

PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-build.sh" --force >"$LOG_DIR/build.out" 2>"$LOG_DIR/build.err"
rc=$?
if [ "$rc" -eq 0 ] && grep -q 'Build OK' "$LOG_DIR/build.out"; then
  check "18.5: EDC_AGENT_CLI=pi runs build orchestrator" 1
else
  check "18.5: EDC_AGENT_CLI=pi runs build orchestrator" 0
  cat "$LOG_DIR/build.out" "$LOG_DIR/build.err"
fi

model_count=$(grep -c -- '--model t18-model' "$PI_CALLS_LOG" 2>/dev/null || true)
if [ "$model_count" -ge 3 ]; then
  check "18.6: pi backend forwards phase model vars" 1
else
  check "18.6: pi backend forwards phase model vars" 0
  cat "$PI_CALLS_LOG" 2>/dev/null || true
fi

fallback_before=$(grep -c -- '--model t18-fallback-model' "$PI_CALLS_LOG" 2>/dev/null || true)
PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_PI_MODEL=t18-fallback-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >"$LOG_DIR/fallback-update.out" 2>"$LOG_DIR/fallback-update.err"
rc=$?
fallback_after=$(grep -c -- '--model t18-fallback-model' "$PI_CALLS_LOG" 2>/dev/null || true)
if [ "$rc" -eq 0 ] && grep -q 'Update OK' "$LOG_DIR/fallback-update.out" && [ "$fallback_after" -gt "$fallback_before" ]; then
  check "18.7: pi backend forwards EDC_PI_MODEL fallback" 1
else
  check "18.7: pi backend forwards EDC_PI_MODEL fallback" 0
  cat "$LOG_DIR/fallback-update.out" "$LOG_DIR/fallback-update.err"
  cat "$PI_CALLS_LOG" 2>/dev/null || true
fi

alias_before=$(grep -c -- '--model gpt-5.5' "$PI_CALLS_LOG" 2>/dev/null || true)
PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_PI_MODEL=gpt-5.5 "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >"$LOG_DIR/alias-update.out" 2>"$LOG_DIR/alias-update.err"
rc=$?
alias_after=$(grep -c -- '--model gpt-5.5' "$PI_CALLS_LOG" 2>/dev/null || true)
if [ "$rc" -eq 0 ] && grep -q 'Update OK' "$LOG_DIR/alias-update.out" && [ "$alias_after" -gt "$alias_before" ]; then
  check "18.8: pi backend forwards EDC_PI_MODEL exactly" 1
else
  check "18.8: pi backend forwards EDC_PI_MODEL exactly" 0
  cat "$LOG_DIR/alias-update.out" "$LOG_DIR/alias-update.err"
  cat "$PI_CALLS_LOG" 2>/dev/null || true
fi

rm -f review-HEAD.md
raw_before=$(grep -c -- '--model gpt-5.5' "$PI_CALLS_LOG" 2>/dev/null || true)
PATH="$TMP/bin:$PATH" "$BASH_BIN" "$SCRIPT" --agent pi --model gpt-5.5 --base HEAD~1 --committed-only >"$LOG_DIR/raw-model-review.out" 2>"$LOG_DIR/raw-model-review.err"
rc=$?
raw_after=$(grep -c -- '--model gpt-5.5' "$PI_CALLS_LOG" 2>/dev/null || true)
if [ "$rc" -eq 0 ] && [ -f review-HEAD.md ] && grep -q 'mock pi review' review-HEAD.md && [ "$raw_after" -gt "$raw_before" ]; then
  check "18.9: raw edc-review.sh accepts --agent/--model and forwards model exactly" 1
else
  check "18.9: raw edc-review.sh accepts --agent/--model and forwards model exactly" 0
  cat "$LOG_DIR/raw-model-review.out" "$LOG_DIR/raw-model-review.err"
  cat "$PI_CALLS_LOG" 2>/dev/null || true
fi

PATH="$TMP/bin:$PATH" PI_FAKE_HANG_AFTER_AGENT_END=1 EDC_AGENT_CLI=pi EDC_UPDATE_TIMEOUT=3 EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >"$LOG_DIR/hang-update.out" 2>"$LOG_DIR/hang-update.err"
rc=$?
if [ "$rc" -eq 0 ] && grep -q 'Update OK' "$LOG_DIR/hang-update.out"; then
  check "18.10: pi backend stops reading after agent_end" 1
else
  check "18.10: pi backend stops reading after agent_end" 0
  cat "$LOG_DIR/hang-update.out" "$LOG_DIR/hang-update.err"
fi

PATH="$TMP/bin:$PATH" PI_FAKE_AGENT_END_ERROR=1 EDC_AGENT_CLI=pi EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >"$LOG_DIR/agent-end-error.out" 2>"$LOG_DIR/agent-end-error.err"
rc=$?
if [ "$rc" -ne 0 ] && grep -q 'provider down' "$LOG_DIR/agent-end-error.err"; then
  check "18.11: pi backend fails on agent_end assistant error" 1
else
  check "18.11: pi backend fails on agent_end assistant error" 0
  cat "$LOG_DIR/agent-end-error.out" "$LOG_DIR/agent-end-error.err"
fi

PATH="$TMP/bin:$PATH" PI_FAKE_AGENT_END_RETRY=1 EDC_AGENT_CLI=pi EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >"$LOG_DIR/agent-end-retry.out" 2>"$LOG_DIR/agent-end-retry.err"
rc=$?
if [ "$rc" -eq 0 ] && grep -q 'Update OK' "$LOG_DIR/agent-end-retry.out"; then
  check "18.12: pi backend allows retryable agent_end to recover" 1
else
  check "18.12: pi backend allows retryable agent_end to recover" 0
  cat "$LOG_DIR/agent-end-retry.out" "$LOG_DIR/agent-end-retry.err"
fi

auth_start=$(date +%s)
PATH="$TMP/bin:$PATH" PI_FAKE_AUTH_TEXT=1 EDC_AGENT_CLI=pi EDC_UPDATE_TIMEOUT=3 EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >"$LOG_DIR/plain-auth.out" 2>"$LOG_DIR/plain-auth.err"
rc=$?
auth_duration=$(( $(date +%s) - auth_start ))
if [ "$rc" -ne 0 ] \
   && [ "$auth_duration" -lt 3 ] \
   && grep -q 'No API key found for azure-openai-responses' "$LOG_DIR/plain-auth.err" \
   && ! grep -q "timed out" "$LOG_DIR/plain-auth.err"; then
  check "18.13: pi backend fails fast on plaintext provider auth errors" 1
else
  check "18.13: pi backend fails fast on plaintext provider auth errors" 0
  printf 'duration=%s rc=%s\n' "$auth_duration" "$rc"
  cat "$LOG_DIR/plain-auth.out" "$LOG_DIR/plain-auth.err"
fi

echo
check_summary "T18"
