#!/usr/bin/env bash
# t18-pi-backend: EDC_AGENT_CLI=pi uses pi CLI for spawned update/review work.
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/plugins/edc/scripts/edc-review.sh"

resolve_bash4() {
  local candidate
  for candidate in "${EDC_BASH:-}" /opt/homebrew/bin/bash /usr/local/bin/bash "$(command -v bash 2>/dev/null || true)" /bin/bash; do
    [ -n "$candidate" ] || continue
    [ -x "$candidate" ] || continue
    if "$candidate" -lc '[ "${BASH_VERSINFO[0]}" -ge 4 ]' 2>/dev/null; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

BASH_BIN="$(resolve_bash4)" || { echo "FAIL: bash >=4 not found"; exit 1; }
export EDC_BASH="$BASH_BIN"

. "$(dirname "$0")/lib/check.sh"
check_init --file
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"; check_cleanup' EXIT

setup_repo() {
  cd "$TMP"
  export GIT_CONFIG_GLOBAL=/dev/null
  export GIT_CONFIG_SYSTEM=/dev/null
  git init -q
  git config user.email test@test.com
  git config user.name Test
  git config commit.gpgsign false
  mkdir -p src
  echo 'one' > src/a.txt
  git add src/a.txt
  git commit -q -m init

  mkdir -p edc-context/modules edc-context/reports .edc/skills/edc-build-impl .edc/skills/edc-update-impl .edc/skills/edc-context-curator-impl .edc/skills/edc-context-curator-edit-impl .edc/skills/edc-review .edc/skills/edc-audit/references
  printf '# Repo\n\n## Module Map\n' > edc-context/index.md
  printf '## Issues\n' > edc-context/reports/issues.md
  printf '## Complexity\n' > edc-context/reports/complexity.md
  printf '# Core\n\n## Files\n' > edc-context/modules/core.md
  cat > edc-context/manifest.json <<EOF
{
  "schemaVersion": 2,
  "sourceCommit": "0000000000000000000000000000000000000000",
  "policy": {"defaultMode": "advisory", "unmatchedPathPolicy": "warn-allow"},
  "modules": [
    {"name":"core", "priority": 10, "doc":"edc-context/modules/core.md", "match":{"prefixes":["src/"]}}
  ]
}
EOF
  printf 'BUILD_SKILL_MARKER\n' > .edc/skills/edc-build-impl/SKILL.md
  printf 'UPDATE_SKILL_MARKER\n' > .edc/skills/edc-update-impl/SKILL.md
  printf 'CURATOR_SKILL_MARKER\n' > .edc/skills/edc-context-curator-impl/SKILL.md
  printf 'CURATOR_EDIT_SKILL_MARKER\n' > .edc/skills/edc-context-curator-edit-impl/SKILL.md
  printf 'REVIEW_SKILL_MARKER\n' > .edc/skills/edc-review/SKILL.md
  printf 'AUDIT_SKILL_MARKER\n' > .edc/skills/edc-audit/SKILL.md
  printf 'AUDIT_SCOPE_MARKER\n' > .edc/skills/edc-audit/references/scope-and-standards.md
  printf 'AUDIT_SMELL_MARKER\n' > .edc/skills/edc-audit/references/smell-baseline.md
  printf 'AUDIT_CHECKS_MARKER\n' > .edc/skills/edc-audit/references/quality-checks.md
  printf 'AUDIT_REPORTING_MARKER\n' > .edc/skills/edc-audit/references/reporting.md
  printf 'METHODOLOGY_MARKER\n' > .edc/skills/edc-review/methodology.md
  printf 'ADVERSARIAL_MARKER\n' > .edc/skills/edc-review/adversarial.md
  printf 'REPORTING_MARKER\n' > .edc/skills/edc-review/reporting.md
  printf 'PATTERNS_MARKER\n' > .edc/skills/edc-review/patterns.md

  echo 'two' > src/a.txt
  git add src/a.txt
  git commit -q -m change
}

write_mock_pi() {
  mkdir -p "$TMP/bin"
  cat > "$TMP/bin/pi" <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> pi-calls.log
prompt=""
for arg in "$@"; do
  case "$arg" in
    @*) prompt="$(cat "${arg#@}")" ;;
  esac
done
write_context() {
  head=$(git rev-parse HEAD)
  mkdir -p edc-context/modules edc-context/reports
  printf '# Repo\n\n## Module Map\n' > edc-context/index.md
  printf '# Core\n\n## Files\n' > edc-context/modules/core.md
  printf '## Issues\n' > edc-context/reports/issues.md
  printf '## Complexity\n' > edc-context/reports/complexity.md
  printf '# Agent Instructions\n\nThis repo ships deep architectural context generated by EDC.\n\nSee [`edc-context/index.md`](edc-context/index.md).\nSee [`edc-context/manifest.json`](edc-context/manifest.json).\n' > AGENTS.md
  cat > edc-context/manifest.json <<EOF
{"schemaVersion":2,"sourceCommit":"$head","policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"modules":[{"name":"core","priority":10,"doc":"edc-context/modules/core.md","match":{"prefixes":["src/"]}}]}
EOF
}
finish_ok() {
  printf '{"type":"result","is_error":false,"result":"ok"}\n'
  if [ "${PI_FAKE_AGENT_END_ERROR:-0}" = "1" ]; then
    printf '{"type":"agent_end","messages":[{"role":"assistant","stopReason":"error","errorMessage":"provider down","content":[{"type":"text","text":""}]}]}\n'
  else
    printf '{"type":"agent_end","messages":[{"role":"assistant","stopReason":"stop","content":[{"type":"text","text":"ok"}]}]}\n'
  fi
  if [ "${PI_FAKE_HANG_AFTER_AGENT_END:-0}" = "1" ]; then
    sleep 5
  fi
  exit 0
}
if printf '%s' "$prompt" | grep -q 'BUILD_SKILL_MARKER'; then
  write_context
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"built context"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'UPDATE_SKILL_MARKER'; then
  write_context
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"updated context"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'CURATOR_EDIT_SKILL_MARKER'; then
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"curator edit"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'CURATOR_SKILL_MARKER'; then
  mkdir -p edc-context/reports
  printf '# Context Curation Report\n\n## Summary\n- mock pi curator\n' > edc-context/reports/context-curation.md
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"curated"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'REVIEW_SKILL_MARKER'; then
  mkdir -p edc-context/review-tasks
  printf '## Summary\n\nmock pi review\n' > edc-context/review-tasks/report-core.md
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"reviewed"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'AUDIT WORKER TASK'; then
  report_path=$(printf '%s\n' "$prompt" | grep '^AUDIT_REPORT_PATH: ' | head -1 | sed 's/^AUDIT_REPORT_PATH: //')
  mkdir -p "$(dirname "$report_path")"
  printf '## Module Audit\n\nmock pi module audit\n' > "$report_path"
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"audited module"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'AUDIT SYNTHESIS TASK'; then
  mkdir -p edc-context/reports
  printf '## Complexity\n\nmock pi audit\n' > edc-context/reports/complexity.md
  printf '## Issues\n\nmock pi audit\n' > edc-context/reports/issues.md
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"audited"}}\n'
  finish_ok
fi
if printf '%s' "$prompt" | grep -q 'AUDIT_SKILL_MARKER'; then
  mkdir -p edc-context/reports
  printf '## Complexity\n\nmock pi audit\n' > edc-context/reports/complexity.md
  printf '## Issues\n\nmock pi audit\n' > edc-context/reports/issues.md
  printf '{"type":"message_update","assistantMessageEvent":{"type":"text_delta","delta":"audited"}}\n'
  finish_ok
fi
printf '{"type":"result","is_error":true,"result":"unexpected prompt"}\n'
exit 1
MOCK
  chmod +x "$TMP/bin/pi"
}

setup_repo
write_mock_pi
PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_KEEP_REVIEW_TASKS=1 "$BASH_BIN" "$SCRIPT" HEAD --base HEAD~1 >out.log 2>err.log
rc=$?

if [ "$rc" -eq 0 ] && [ -f review-HEAD.md ] && grep -q 'mock pi review' review-HEAD.md; then
  check "18.1: EDC_AGENT_CLI=pi completes stale-context review via pi CLI" 1
else
  check "18.1: EDC_AGENT_CLI=pi completes stale-context review via pi CLI" 0
  cat out.log err.log
fi

if [ -f pi-calls.log ] && grep -q -- '--mode json' pi-calls.log && grep -q -- '--no-context-files' pi-calls.log; then
  check "18.2: pi backend uses json clean-slate CLI mode" 1
else
  check "18.2: pi backend uses json clean-slate CLI mode" 0
  cat pi-calls.log 2>/dev/null || true
fi

PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >update.out 2>update.err
rc=$?
if [ "$rc" -eq 0 ] && grep -q 'Update OK' update.out; then
  check "18.3: EDC_AGENT_CLI=pi runs update orchestrator" 1
else
  check "18.3: EDC_AGENT_CLI=pi runs update orchestrator" 0
  cat update.out update.err
fi

PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-audit.sh" >audit.out 2>audit.err
rc=$?
if [ "$rc" -eq 0 ] && grep -q 'Audit reports:' audit.out; then
  check "18.4: EDC_AGENT_CLI=pi runs audit orchestrator" 1
else
  check "18.4: EDC_AGENT_CLI=pi runs audit orchestrator" 0
  cat audit.out audit.err
fi

PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-build.sh" --force >build.out 2>build.err
rc=$?
if [ "$rc" -eq 0 ] && grep -q 'Build OK' build.out; then
  check "18.5: EDC_AGENT_CLI=pi runs build orchestrator" 1
else
  check "18.5: EDC_AGENT_CLI=pi runs build orchestrator" 0
  cat build.out build.err
fi

model_count=$(grep -c -- '--model t18-model' pi-calls.log 2>/dev/null || true)
if [ "$model_count" -ge 3 ]; then
  check "18.6: pi backend forwards phase model vars" 1
else
  check "18.6: pi backend forwards phase model vars" 0
  cat pi-calls.log 2>/dev/null || true
fi

fallback_before=$(grep -c -- '--model t18-fallback-model' pi-calls.log 2>/dev/null || true)
PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_PI_MODEL=t18-fallback-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >fallback-update.out 2>fallback-update.err
rc=$?
fallback_after=$(grep -c -- '--model t18-fallback-model' pi-calls.log 2>/dev/null || true)
if [ "$rc" -eq 0 ] && grep -q 'Update OK' fallback-update.out && [ "$fallback_after" -gt "$fallback_before" ]; then
  check "18.7: pi backend forwards EDC_PI_MODEL fallback" 1
else
  check "18.7: pi backend forwards EDC_PI_MODEL fallback" 0
  cat fallback-update.out fallback-update.err
  cat pi-calls.log 2>/dev/null || true
fi

alias_before=$(grep -c -- '--model gpt-5.5' pi-calls.log 2>/dev/null || true)
PATH="$TMP/bin:$PATH" EDC_AGENT_CLI=pi EDC_PI_MODEL=gpt-5.5 "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >alias-update.out 2>alias-update.err
rc=$?
alias_after=$(grep -c -- '--model gpt-5.5' pi-calls.log 2>/dev/null || true)
if [ "$rc" -eq 0 ] && grep -q 'Update OK' alias-update.out && [ "$alias_after" -gt "$alias_before" ]; then
  check "18.8: pi backend forwards EDC_PI_MODEL exactly" 1
else
  check "18.8: pi backend forwards EDC_PI_MODEL exactly" 0
  cat alias-update.out alias-update.err
  cat pi-calls.log 2>/dev/null || true
fi

rm -f review-HEAD.md
raw_before=$(grep -c -- '--model gpt-5.5' pi-calls.log 2>/dev/null || true)
PATH="$TMP/bin:$PATH" "$BASH_BIN" "$SCRIPT" --agent pi --model gpt-5.5 --base HEAD~1 >raw-model-review.out 2>raw-model-review.err
rc=$?
raw_after=$(grep -c -- '--model gpt-5.5' pi-calls.log 2>/dev/null || true)
if [ "$rc" -eq 0 ] && [ -f review-HEAD.md ] && grep -q 'mock pi review' review-HEAD.md && [ "$raw_after" -gt "$raw_before" ]; then
  check "18.9: raw edc-review.sh accepts --agent/--model and forwards model exactly" 1
else
  check "18.9: raw edc-review.sh accepts --agent/--model and forwards model exactly" 0
  cat raw-model-review.out raw-model-review.err
  cat pi-calls.log 2>/dev/null || true
fi

PATH="$TMP/bin:$PATH" PI_FAKE_HANG_AFTER_AGENT_END=1 EDC_AGENT_CLI=pi EDC_UPDATE_TIMEOUT=3 EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >hang-update.out 2>hang-update.err
rc=$?
if [ "$rc" -eq 0 ] && grep -q 'Update OK' hang-update.out; then
  check "18.10: pi backend stops reading after agent_end" 1
else
  check "18.10: pi backend stops reading after agent_end" 0
  cat hang-update.out hang-update.err
fi

PATH="$TMP/bin:$PATH" PI_FAKE_AGENT_END_ERROR=1 EDC_AGENT_CLI=pi EDC_BUILD_MODEL=t18-model EDC_REVIEW_MODEL=t18-model "$BASH_BIN" "$ROOT/plugins/edc/scripts/edc-update.sh" --base HEAD~1 >agent-end-error.out 2>agent-end-error.err
rc=$?
if [ "$rc" -ne 0 ] && grep -q 'provider down' agent-end-error.err; then
  check "18.11: pi backend fails on agent_end assistant error" 1
else
  check "18.11: pi backend fails on agent_end assistant error" 0
  cat agent-end-error.out agent-end-error.err
fi

echo
check_summary "T18"
