#!/usr/bin/env bash
# t32-runtime-curator-step: build/update orchestrators must run the context
# curator as a deterministic runtime step, not merely rely on prompt text.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT_BUILD="$ROOT/plugins/edc/scripts/edc-build.sh"
SCRIPT_UPDATE="$ROOT/plugins/edc/scripts/edc-update.sh"
TMP="$(mktemp -d)"
MOCK_BIN="$TMP/bin"
trap 'rm -rf "$TMP"' EXIT

BASH_BIN="${BASH_BIN:-bash}"

mkdir -p "$MOCK_BIN"
cat > "$MOCK_BIN/claude" <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
prompt=$(cat)
previous=""
for arg in "$@"; do
  if [ "$previous" = "--system-prompt-file" ]; then
    prompt=$(cat "$arg")
    break
  fi
  previous="$arg"
done
LOG="${EDC_T32_LOG:?}"
write_context() {
  local head
  head=$(git rev-parse HEAD)
  mkdir -p edc-context/modules edc-context/reports edc-context/build
  printf '<!-- t32 -->\n# Stub\n\n## Route by path/task\n' > edc-context/index.md
  printf '<!-- t32 -->\n# Core\n\n## Scope\n' > edc-context/modules/core.md
  printf '## Known Issues\n' > edc-context/reports/issues.md
  printf '## Summary\n' > edc-context/reports/complexity.md
  printf '{}\n' > edc-context/build/build.json
  printf '# Agent Instructions\n\nThis repo ships deep architectural context generated by EDC.\n\nSee [`edc-context/index.md`](edc-context/index.md).\nSee [`edc-context/manifest.json`](edc-context/manifest.json).\n' > AGENTS.md
  cat > edc-context/manifest.json <<EOF
{"schemaVersion":2,"edcVersion":"1.1.1","generatedAt":"2026-01-01T00:00:00Z","sourceCommit":"$head","modules":[{"name":"core","doc":"edc-context/modules/core.md","priority":100,"match":{"prefixes":["src/"]}}],"contextless":{"entries":[{"id":"generated-context","globs":["AGENTS.md","edc-context/**"],"reason":"generated context","reviewPolicy":"account-only"}]},"unmapped":{"allowedGlobs":[]},"policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"repoContextFile":"edc-context/index.md","reports":{"issues":"edc-context/reports/issues.md","complexity":"edc-context/reports/complexity.md"},"build":{"buildInfoFile":"edc-context/build/build.json"},"coverage":{"contextMappedFileCount":1,"contextlessFileCount":0,"uncoveredFileCount":0,"ambiguousPathCount":0,"ignoredFileCount":0,"mappedFileCount":1,"unmappedFileCount":0}}
EOF
}
if [[ "$prompt" == *"BUILD DISCOVERY TASK"* ]]; then
  echo build >> "$LOG"
  output=$(printf '%s\n' "$prompt" | grep '^DISCOVERY_OUTPUT: ' | sed 's/^DISCOVERY_OUTPUT: //')
  mkdir -p "$(dirname "$output")"
  printf '{"modules":[{"name":"core","paths":["src/"],"approxLoc":1}]}\n' > "$output"
  exit 0
fi
if [[ "$prompt" == *"MODULE CONTEXT TASK"* ]]; then
  output=$(printf '%s\n' "$prompt" | grep '^OUTPUT: ' | head -1 | sed 's/^OUTPUT: //')
  mkdir -p "$(dirname "$output")"
  printf '# Core\n\n## Scope\n\nMock.\n' > "$output"
  exit 0
fi
if [[ "$prompt" == *"CROSS-MODULE SYNTHESIS TASK"* ]]; then
  output=$(printf '%s\n' "$prompt" | grep '^OUTPUT: ' | sed 's/^OUTPUT: //')
  printf '## Flows\n\nMock.\n' > "$output"
  exit 0
fi
if [[ "$prompt" == *"BUILD ASSEMBLY TASK"* ]]; then
  index_output=$(printf '%s\n' "$prompt" | grep '^INDEX_OUTPUT: ' | sed 's/^INDEX_OUTPUT: //')
  partial_output=$(printf '%s\n' "$prompt" | grep '^PARTIAL_MANIFEST_OUTPUT: ' | sed 's/^PARTIAL_MANIFEST_OUTPUT: //')
  build_output=$(printf '%s\n' "$prompt" | grep '^BUILD_INFO_OUTPUT: ' | sed 's/^BUILD_INFO_OUTPUT: //')
  agents_output=$(printf '%s\n' "$prompt" | grep '^AGENT_ENTRYPOINT_OUTPUT: ' | sed 's/^AGENT_ENTRYPOINT_OUTPUT: //')
  mkdir -p "$(dirname "$index_output")" "$(dirname "$build_output")" "$(dirname "$agents_output")"
  printf '# Stub\n\n## How to use\n\nRead routes.\n\n## Route by path/task\n\n- src: core\n\n## Critical global invariants\n\n- mock\n\n## Cross-module coupling / blast radius\n\n- mock\n' > "$index_output"
  printf '{"schemaVersion":2,"edcVersion":"1.1.1","repoContextFile":"edc-context/index.md","reports":{"issues":"edc-context/reports/issues.md","complexity":"edc-context/reports/complexity.md"},"build":{"buildInfoFile":"edc-context/build/build.json"},"policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"modules":[{"name":"core","doc":"edc-context/modules/core.md","summary":"mock","priority":100,"match":{"prefixes":["src/"]}}],"unmapped":{"allowedGlobs":["*"]}}\n' > "$partial_output"
  printf '{}\n' > "$build_output"
  printf '# Agent Instructions\n\nThis repo ships deep architectural context generated by EDC.\n\nSee [`edc-context/index.md`](edc-context/index.md).\nSee [`edc-context/manifest.json`](edc-context/manifest.json).\n' > "$agents_output"
  exit 0
fi
if [[ "$prompt" == *"AUDIT WORKER TASK"* ]]; then
  report=$(printf '%s\n' "$prompt" | grep '^AUDIT_REPORT_PATH: ' | head -1 | sed 's/^AUDIT_REPORT_PATH: //')
  mkdir -p "$(dirname "$report")"
  printf '## Module Audit\n\nMock.\n' > "$report"
  exit 0
fi
if [[ "$prompt" == *"AUDIT SYNTHESIS TASK"* ]]; then
  complexity=$(printf '%s\n' "$prompt" | grep '^CANONICAL_COMPLEXITY_REPORT: ' | head -1 | sed 's/^CANONICAL_COMPLEXITY_REPORT: //')
  issues=$(printf '%s\n' "$prompt" | grep '^CANONICAL_ISSUES_REPORT: ' | head -1 | sed 's/^CANONICAL_ISSUES_REPORT: //')
  mkdir -p "$(dirname "$complexity")"
  printf '## Summary\n\nMock.\n' > "$complexity"
  printf '## Known Issues\n\nMock.\n' > "$issues"
  exit 0
fi
if [[ "$prompt" == *"name: edc-build-impl"* ]]; then
  echo build >> "$LOG"
  write_context
  exit 0
fi
if [[ "$prompt" == *"name: edc-update-impl"* ]]; then
  echo update >> "$LOG"
  write_context
  exit 0
fi
if [[ "$prompt" == *"name: edc-context-curator-edit-impl"* ]]; then
  echo curator-edit >> "$LOG"
  exit 0
fi
if [[ "$prompt" == *"name: edc-context-curator-impl"* ]] || [[ "$prompt" == *"Context Curator"* ]]; then
  echo curator >> "$LOG"
  mkdir -p edc-context/reports
  if [ "${EDC_T32_CURATOR_MODE:-ok}" = "missing-report" ]; then
    exit 0
  fi
  printf '# Context Curation Report\n\n## Summary\n- runtime curator ran\n' > edc-context/reports/context-curation.md
  exit 0
fi

echo "MOCK ERROR: unrecognized prompt" >&2
echo "$prompt" >&2
exit 1
MOCK
chmod +x "$MOCK_BIN/claude"

setup_repo() {
  local dir="$1"
  rm -rf "$dir"
  mkdir -p "$dir/src"
  cd "$dir"
  export GIT_CONFIG_GLOBAL=/dev/null
  export GIT_CONFIG_SYSTEM=/dev/null
  git init -q -b main
  git config user.email t@t.com
  git config user.name T
  git config commit.gpgsign false
  printf 'src\n' > src/main.py
  git add src/main.py
  git commit -q -m init
  mkdir -p .edc/skills/edc-build-impl .edc/skills/edc-update-impl .edc/skills/edc-context-curator-impl .edc/skills/edc-context-curator-edit-impl .edc/skills/edc-module-context-impl/resources .edc/skills/edc-audit/references
  printf '%s\n' '---' 'name: edc-build-impl' '---' > .edc/skills/edc-build-impl/SKILL.md
  printf '%s\n' '---' 'name: edc-update-impl' '---' > .edc/skills/edc-update-impl/SKILL.md
  printf '%s\n' '---' 'name: edc-context-curator-impl' '---' '# Context Curator' > .edc/skills/edc-context-curator-impl/SKILL.md
  printf '%s\n' '---' 'name: edc-context-curator-edit-impl' '---' '# Context Curator Edit' > .edc/skills/edc-context-curator-edit-impl/SKILL.md
  printf '# Module Context\n' > .edc/skills/edc-module-context-impl/SKILL.md
  printf '# Audit\n' > .edc/skills/edc-audit/SKILL.md
  for ref in scope-and-standards smell-baseline quality-checks reporting; do printf '# %s\n' "$ref" > ".edc/skills/edc-audit/references/$ref.md"; done
  : > "$TMP/log"
}

# build path: build subprocess then curator subprocess
REPO_BUILD="$TMP/build-repo"
setup_repo "$REPO_BUILD"
out=$(PATH="$MOCK_BIN:$PATH" EDC_AGENT_CLI=claude EDC_T32_LOG="$TMP/log" "$BASH_BIN" "$SCRIPT_BUILD" 2>&1)
if [ ! -e edc-context/reports/context-curation.md ] \
   && grep -qx 'build' "$TMP/log" \
   && grep -qx 'curator' "$TMP/log" \
   && grep -qx 'curator-edit' "$TMP/log" \
   && [ "$(grep -c '^curator$' "$TMP/log")" -eq 1 ]; then
  echo "PASS: build orchestrator runs runtime curator and removes intermediate report"
else
  echo "FAIL: build orchestrator did not run runtime curator or remove intermediate report"
  echo "$out"
  cat "$TMP/log"
  exit 1
fi

# update path: update subprocess then curator subprocess
REPO_UPDATE="$TMP/update-repo"
setup_repo "$REPO_UPDATE"
PATH="$MOCK_BIN:$PATH" EDC_AGENT_CLI=claude EDC_T32_LOG="$TMP/log" "$BASH_BIN" "$SCRIPT_BUILD" >/dev/null 2>&1
rm -f edc-context/reports/context-curation.md
printf 'more\n' > src/extra.py
git add src/extra.py
git commit -q -m more
: > "$TMP/log"
out=$(PATH="$MOCK_BIN:$PATH" EDC_AGENT_CLI=claude EDC_T32_LOG="$TMP/log" "$BASH_BIN" "$SCRIPT_UPDATE" --base HEAD~1 2>&1)
if [ ! -e edc-context/reports/context-curation.md ] \
   && grep -qx 'update' "$TMP/log" \
   && grep -qx 'curator' "$TMP/log" \
   && grep -qx 'curator-edit' "$TMP/log"; then
  echo "PASS: update orchestrator runs runtime curator and removes intermediate report"
else
  echo "FAIL: update orchestrator did not run runtime curator or remove intermediate report"
  echo "$out"
  cat "$TMP/log"
  exit 1
fi

# curator success without report is a failed build/update
REPO_FAIL="$TMP/fail-repo"
setup_repo "$REPO_FAIL"
: > "$TMP/log"
set +e
out=$(PATH="$MOCK_BIN:$PATH" EDC_AGENT_CLI=claude EDC_T32_LOG="$TMP/log" EDC_T32_CURATOR_MODE=missing-report "$BASH_BIN" "$SCRIPT_BUILD" 2>&1)
rc=$?
set -e
if [ "$rc" -ne 0 ] && echo "$out" | grep -q 'context curator report missing'; then
  echo "PASS: missing curator report fails build"
else
  echo "FAIL: missing curator report should fail build"
  echo "rc=$rc"
  echo "$out"
  cat "$TMP/log"
  exit 1
fi

echo "All T32 checks passed."
