#!/usr/bin/env bash
# t33-runtime-curator-edit-mode: curator edit mode runs as a second constrained
# runtime agent, may edit index/modules, and is blocked from manifest/source edits.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT_BUILD="$ROOT/plugins/edc/scripts/edc-build.sh"
TMP="$(mktemp -d)"
MOCK_BIN="$TMP/bin"
trap 'rm -rf "$TMP"' EXIT

BASH_BIN="${BASH_BIN:-bash}"

mkdir -p "$MOCK_BIN"
cat > "$MOCK_BIN/claude" <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
prompt=$(cat)
previous=""
for arg in "$@"; do
  if [ "$previous" = "--system-prompt-file" ]; then
    prompt=$(cat "$arg")
    break
  fi
  previous="$arg"
done
LOG="${EDC_T33_LOG:?}"
write_context() {
  local head
  head=$(git rev-parse HEAD)
  mkdir -p edc-context/modules edc-context/reports edc-context/build
  printf '<!-- t33 -->\n# Stub\n\n## Route by path/task\n' > edc-context/index.md
  printf '<!-- t33 -->\n# Core\n\n## Scope\n' > edc-context/modules/core.md
  printf '## Known Issues\n' > edc-context/reports/issues.md
  printf '## Summary\n' > edc-context/reports/complexity.md
  printf '{}\n' > edc-context/build/build.json
  printf '# Agent Instructions\n\nThis repo ships deep architectural context generated by EDC.\n\nSee [`edc-context/index.md`](edc-context/index.md).\nSee [`edc-context/manifest.json`](edc-context/manifest.json).\n' > AGENTS.md
  cat > edc-context/manifest.json <<EOF
{"schemaVersion":2,"edcVersion":"1.1.1","generatedAt":"2026-01-01T00:00:00Z","sourceCommit":"$head","modules":[{"name":"core","doc":"edc-context/modules/core.md","priority":100,"match":{"prefixes":["src/"]}}],"contextless":{"entries":[{"id":"generated-context","globs":["AGENTS.md","edc-context/**"],"reason":"generated context","reviewPolicy":"account-only"}]},"unmapped":{"allowedGlobs":[]},"policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"repoContextFile":"edc-context/index.md","reports":{"issues":"edc-context/reports/issues.md","complexity":"edc-context/reports/complexity.md"},"build":{"buildInfoFile":"edc-context/build/build.json"},"coverage":{"contextMappedFileCount":1,"contextlessFileCount":0,"uncoveredFileCount":0,"ambiguousPathCount":0,"ignoredFileCount":0,"mappedFileCount":1,"unmappedFileCount":0}}
EOF
}
if [[ "$prompt" == *"BUILD DISCOVERY TASK"* ]]; then
  echo build >> "$LOG"
  output=$(printf '%s\n' "$prompt" | grep '^DISCOVERY_OUTPUT: ' | sed 's/^DISCOVERY_OUTPUT: //')
  mkdir -p "$(dirname "$output")"
  printf '{"modules":[{"name":"core","paths":["src/"],"approxLoc":1}]}\n' > "$output"
  exit 0
fi
if [[ "$prompt" == *"MODULE CONTEXT TASK"* ]]; then
  output=$(printf '%s\n' "$prompt" | grep '^OUTPUT: ' | head -1 | sed 's/^OUTPUT: //')
  mkdir -p "$(dirname "$output")"
  printf '# Core\n\n## Scope\n\nMock.\n' > "$output"
  exit 0
fi
if [[ "$prompt" == *"CROSS-MODULE SYNTHESIS TASK"* ]]; then
  output=$(printf '%s\n' "$prompt" | grep '^OUTPUT: ' | sed 's/^OUTPUT: //')
  printf '## Flows\n\nMock.\n' > "$output"
  exit 0
fi
if [[ "$prompt" == *"BUILD ASSEMBLY TASK"* ]]; then
  index_output=$(printf '%s\n' "$prompt" | grep '^INDEX_OUTPUT: ' | sed 's/^INDEX_OUTPUT: //')
  partial_output=$(printf '%s\n' "$prompt" | grep '^PARTIAL_MANIFEST_OUTPUT: ' | sed 's/^PARTIAL_MANIFEST_OUTPUT: //')
  build_output=$(printf '%s\n' "$prompt" | grep '^BUILD_INFO_OUTPUT: ' | sed 's/^BUILD_INFO_OUTPUT: //')
  agents_output=$(printf '%s\n' "$prompt" | grep '^AGENT_ENTRYPOINT_OUTPUT: ' | sed 's/^AGENT_ENTRYPOINT_OUTPUT: //')
  mkdir -p "$(dirname "$index_output")" "$(dirname "$build_output")" "$(dirname "$agents_output")"
  printf '# Stub\n\n## How to use\n\nRead routes.\n\n## Route by path/task\n\n- src: core\n\n## Critical global invariants\n\n- mock\n\n## Cross-module coupling / blast radius\n\n- mock\n' > "$index_output"
  printf '{"schemaVersion":2,"edcVersion":"1.1.1","repoContextFile":"edc-context/index.md","reports":{"issues":"edc-context/reports/issues.md","complexity":"edc-context/reports/complexity.md"},"build":{"buildInfoFile":"edc-context/build/build.json"},"policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"modules":[{"name":"core","doc":"edc-context/modules/core.md","summary":"mock","priority":100,"match":{"prefixes":["src/"]}}],"unmapped":{"allowedGlobs":["*"]}}\n' > "$partial_output"
  printf '{}\n' > "$build_output"
  printf '# Agent Instructions\n\nThis repo ships deep architectural context generated by EDC.\n\nSee [`edc-context/index.md`](edc-context/index.md).\nSee [`edc-context/manifest.json`](edc-context/manifest.json).\n' > "$agents_output"
  exit 0
fi
if [[ "$prompt" == *"AUDIT WORKER TASK"* ]]; then
  report=$(printf '%s\n' "$prompt" | grep '^AUDIT_REPORT_PATH: ' | head -1 | sed 's/^AUDIT_REPORT_PATH: //')
  mkdir -p "$(dirname "$report")"
  printf '## Module Audit\n\nMock.\n' > "$report"
  exit 0
fi
if [[ "$prompt" == *"AUDIT SYNTHESIS TASK"* ]]; then
  complexity=$(printf '%s\n' "$prompt" | grep '^CANONICAL_COMPLEXITY_REPORT: ' | head -1 | sed 's/^CANONICAL_COMPLEXITY_REPORT: //')
  issues=$(printf '%s\n' "$prompt" | grep '^CANONICAL_ISSUES_REPORT: ' | head -1 | sed 's/^CANONICAL_ISSUES_REPORT: //')
  mkdir -p "$(dirname "$complexity")"
  printf '## Summary\n\nMock.\n' > "$complexity"
  printf '## Known Issues\n\nMock.\n' > "$issues"
  exit 0
fi
if [[ "$prompt" == *"name: edc-build-impl"* ]]; then
  echo build >> "$LOG"
  write_context
  exit 0
fi
if [[ "$prompt" == *"name: edc-context-curator-edit-impl"* ]]; then
  echo curator-edit >> "$LOG"
  case "${EDC_T33_EDIT_MODE:-ok}" in
    ok)
      printf '\n- edited by curator\n' >> edc-context/index.md
      ;;
    manifest)
      printf '\n"oops": true\n' >> edc-context/manifest.json
      ;;
    source)
      printf '\nmalicious\n' >> src/main.py
      ;;
  esac
  exit 0
fi
if [[ "$prompt" == *"name: edc-context-curator-impl"* ]]; then
  echo curator-report >> "$LOG"
  mkdir -p edc-context/reports
  printf '# Context Curation Report\n\n## Summary\n- t33 report\n\n## Findings\n\n### low: index can be shorter\n- severity: low\n- confidence: high\n- location: edc-context/index.md\n- issue: test fixture\n- recommendation: doc-only edit\n' > edc-context/reports/context-curation.md
  exit 0
fi

echo "MOCK ERROR: unrecognized prompt" >&2
echo "$prompt" >&2
exit 1
MOCK
chmod +x "$MOCK_BIN/claude"

setup_repo() {
  local dir="$1"
  rm -rf "$dir"
  mkdir -p "$dir/src"
  cd "$dir"
  export GIT_CONFIG_GLOBAL=/dev/null
  export GIT_CONFIG_SYSTEM=/dev/null
  git init -q -b main
  git config user.email t@t.com
  git config user.name T
  git config commit.gpgsign false
  printf 'src\n' > src/main.py
  mkdir -p .edc/skills/edc-build-impl .edc/skills/edc-context-curator-impl .edc/skills/edc-context-curator-edit-impl .edc/skills/edc-module-context-impl/resources .edc/skills/edc-audit/references
  printf '%s\n' '---' 'name: edc-build-impl' '---' > .edc/skills/edc-build-impl/SKILL.md
  printf '%s\n' '---' 'name: edc-context-curator-impl' '---' '# Context Curator' > .edc/skills/edc-context-curator-impl/SKILL.md
  printf '%s\n' '---' 'name: edc-context-curator-edit-impl' '---' '# Context Curator Edit' > .edc/skills/edc-context-curator-edit-impl/SKILL.md
  printf '# Module Context\n' > .edc/skills/edc-module-context-impl/SKILL.md
  printf '# Audit\n' > .edc/skills/edc-audit/SKILL.md
  for ref in scope-and-standards smell-baseline quality-checks reporting; do printf '# %s\n' "$ref" > ".edc/skills/edc-audit/references/$ref.md"; done
  git add src/main.py
  git commit -q -m init
  : > "$TMP/log"
}

REPO_OK="$TMP/edit-ok"
setup_repo "$REPO_OK"
out=$(PATH="$MOCK_BIN:$PATH" EDC_AGENT_CLI=claude EDC_T33_LOG="$TMP/log" "$BASH_BIN" "$SCRIPT_BUILD" 2>&1)
if [ ! -e edc-context/reports/context-curation.md ] \
   && grep -qx 'curator-report' "$TMP/log" \
   && grep -qx 'curator-edit' "$TMP/log" \
   && grep -q 'edited by curator' edc-context/index.md; then
  echo "PASS: curator edit mode applies allowed index/module edits and removes intermediate report"
else
  echo "FAIL: curator edit mode did not apply allowed edit or remove intermediate report"
  echo "$out"
  cat "$TMP/log"
  exit 1
fi

REPO_MANIFEST="$TMP/edit-manifest"
setup_repo "$REPO_MANIFEST"
set +e
out=$(PATH="$MOCK_BIN:$PATH" EDC_AGENT_CLI=claude EDC_T33_LOG="$TMP/log" EDC_T33_EDIT_MODE=manifest "$BASH_BIN" "$SCRIPT_BUILD" 2>&1)
rc=$?
set -e
if [ "$rc" -ne 0 ] && echo "$out" | grep -q 'context curator edit touched forbidden paths' && echo "$out" | grep -q 'edc-context/manifest.json'; then
  echo "PASS: curator edit mode blocks manifest edits"
else
  echo "FAIL: curator edit mode should block manifest edits"
  echo "rc=$rc"
  echo "$out"
  cat "$TMP/log"
  exit 1
fi

REPO_SOURCE="$TMP/edit-source"
setup_repo "$REPO_SOURCE"
set +e
out=$(PATH="$MOCK_BIN:$PATH" EDC_AGENT_CLI=claude EDC_T33_LOG="$TMP/log" EDC_T33_EDIT_MODE=source "$BASH_BIN" "$SCRIPT_BUILD" 2>&1)
rc=$?
set -e
if [ "$rc" -ne 0 ] && echo "$out" | grep -q 'context curator edit touched forbidden paths' && echo "$out" | grep -q 'src/main.py'; then
  echo "PASS: curator edit mode blocks source edits"
else
  echo "FAIL: curator edit mode should block source edits"
  echo "rc=$rc"
  echo "$out"
  cat "$TMP/log"
  exit 1
fi

echo "All T33 checks passed."
