#!/usr/bin/env bash
# Runtime robustness: canonical inventory, transactional install, preflight, and structured reasons.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
. "$ROOT/tests/hardening/lib/check.sh"
check_init

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"; check_cleanup' EXIT

PLUGIN_ROOT="$ROOT/plugins/edc"
RUNTIME_CLI="$PLUGIN_ROOT/hooks/lib/runtime-manifest.mjs"

make_repo() {
  local repo="$1"
  mkdir -p "$repo"
  git -C "$repo" init -q
  git -C "$repo" config user.email test@example.invalid
  git -C "$repo" config user.name test
  git -C "$repo" config commit.gpgsign false
  cat >"$repo/AGENTS.md" <<'EOF'
# Agent Instructions

This repo ships deep architectural context generated by EDC. Read this file at session start before touching code.
EOF
  mkdir -p "$repo/edc-context/modules" "$repo/edc-context/reports" "$repo/edc-context/build"
  cat >"$repo/edc-context/index.md" <<'EOF'
# EDC context index
## Module table
EOF
  cat >"$repo/edc-context/manifest.json" <<'EOF'
{
  "schemaVersion": 2,
  "edcVersion": "test",
  "repoContextFile": "edc-context/index.md",
  "reports": { "issues": "edc-context/reports/issues.md", "complexity": "edc-context/reports/complexity.md" },
  "build": { "buildInfoFile": "edc-context/build/build.json" },
  "policy": { "defaultMode": "advisory", "unmatchedPathPolicy": "warn-allow" },
  "modules": [
    { "name": "sample", "doc": "edc-context/modules/sample.md", "priority": 100, "match": { "prefixes": ["src/"] } }
  ],
  "unmapped": { "allowedGlobs": [] },
  "coverage": { "ignoreGlobs": [] },
  "sourceCommit": "test"
}
EOF
  cat >"$repo/edc-context/modules/sample.md" <<'EOF'
# sample
## Scope
EOF
  git -C "$repo" add AGENTS.md edc-context
  git -C "$repo" commit -qm init
}

if [ -x "$RUNTIME_CLI" ] && node "$RUNTIME_CLI" inventory-check "$PLUGIN_ROOT" >/"$TMP/inventory.json" 2>"$TMP/inventory.err"; then
  check "canonical runtime inventory validates and sources exist" "1"
else
  check "canonical runtime inventory validates and sources exist" "0"
  cat "$TMP/inventory.err" 2>/dev/null || true
fi

REPO1="$TMP/source-install"
make_repo "$REPO1"
if node -e "import { installOrchestratorScript } from '$PLUGIN_ROOT/hooks/lib/route.mjs'; installOrchestratorScript('$REPO1', '$PLUGIN_ROOT');" \
  && [ -x "$REPO1/.edc/scripts/edc-review.sh" ] \
  && [ -f "$REPO1/.edc/hooks/lib/worker-manifest.mjs" ] \
  && [ -f "$REPO1/.edc/runtime-metadata.json" ]; then
  check "source project install writes complete runtime and metadata" "1"
else
  check "source project install writes complete runtime and metadata" "0"
fi

PACK_HOME="$TMP/pack-home"
mkdir -p "$PACK_HOME"
if HOME="$PACK_HOME" CI=1 SHELL=/bin/zsh bash "$ROOT/install.sh" --agent claude --no-path >/"$TMP/pack-install.out" 2>&1 \
  && [ -x "$PACK_HOME/.edc/scripts/edc" ] \
  && [ -f "$PACK_HOME/.edc/hooks/lib/worker-manifest.mjs" ] \
  && [ -f "$PACK_HOME/.edc/runtime-metadata.json" ]; then
  check "terminal/package install consumes runtime inventory" "1"
else
  check "terminal/package install consumes runtime inventory" "0"
  cat "$TMP/pack-install.out"
fi

REPO2="$TMP/missing-helper"
make_repo "$REPO2"
node -e "import { installOrchestratorScript } from '$PLUGIN_ROOT/hooks/lib/route.mjs'; installOrchestratorScript('$REPO2', '$PLUGIN_ROOT');"
rm -f "$REPO2/.edc/hooks/lib/worker-manifest.mjs"
mkdir -p "$TMP/bin"
cat >"$TMP/bin/claude" <<'EOF'
#!/usr/bin/env bash
echo called >>"${FAKE_MODEL_CALLED:?}"
exit 0
EOF
chmod +x "$TMP/bin/claude"
before_index=$(shasum -a 256 "$REPO2/edc-context/index.md" | awk '{print $1}')
before_manifest=$(shasum -a 256 "$REPO2/edc-context/manifest.json" | awk '{print $1}')
set +e
(
  cd "$REPO2"
  PATH="$TMP/bin:$PATH" FAKE_MODEL_CALLED="$TMP/model-called" EDC_AGENT_CLI=claude bash .edc/scripts/edc-review.sh --full >"$TMP/missing.out" 2>&1
)
missing_rc=$?
set -e
after_index=$(shasum -a 256 "$REPO2/edc-context/index.md" | awk '{print $1}')
after_manifest=$(shasum -a 256 "$REPO2/edc-context/manifest.json" | awk '{print $1}')
if [ "$missing_rc" -ne 0 ] \
  && grep -q 'runtime-install-incomplete' "$TMP/missing.out" \
  && [ ! -f "$TMP/model-called" ] \
  && [ "$before_index" = "$after_index" ] \
  && [ "$before_manifest" = "$after_manifest" ]; then
  check "missing runtime helper fails before context/model work" "1"
else
  check "missing runtime helper fails before context/model work" "0"
  cat "$TMP/missing.out"
fi

REPO2B="$TMP/no-implicit-repair"
make_repo "$REPO2B"
node -e "import { installOrchestratorScript } from '$PLUGIN_ROOT/hooks/lib/route.mjs'; installOrchestratorScript('$REPO2B', '$PLUGIN_ROOT');"
rm -f "$REPO2B/.edc/hooks/lib/worker-manifest.mjs" "$TMP/model-called"
set +e
(
  cd "$REPO2B"
  PATH="$TMP/bin:$PATH" FAKE_MODEL_CALLED="$TMP/model-called" EDC_PLUGIN_ROOT="$PLUGIN_ROOT" EDC_AGENT_CLI=claude bash .edc/scripts/edc-review.sh --full >"$TMP/no-implicit-repair.out" 2>&1
)
no_repair_rc=$?
set -e
if [ "$no_repair_rc" -ne 0 ] \
  && grep -q 'runtime-install-incomplete' "$TMP/no-implicit-repair.out" \
  && [ ! -e "$TMP/model-called" ] \
  && [ ! -e "$REPO2B/.edc/hooks/lib/worker-manifest.mjs" ]; then
  check "runtime preflight fails closed instead of implicitly repairing" "1"
else
  check "runtime preflight fails closed instead of implicitly repairing" "0"
  cat "$TMP/no-implicit-repair.out"
fi

REPO3="$TMP/corrupt-helper"
make_repo "$REPO3"
node -e "import { installOrchestratorScript } from '$PLUGIN_ROOT/hooks/lib/route.mjs'; installOrchestratorScript('$REPO3', '$PLUGIN_ROOT');"
printf 'export const = broken\n' >"$REPO3/.edc/hooks/lib/worker-manifest.mjs"
if ! node "$RUNTIME_CLI" preflight "$REPO3" >/"$TMP/corrupt.out" 2>&1 \
  && grep -q 'runtime-integrity-mismatch' "$TMP/corrupt.out"; then
  check "corrupt helper returns structured integrity reason" "1"
else
  check "corrupt helper returns structured integrity reason" "0"
  cat "$TMP/corrupt.out"
fi

REPO3B="$TMP/valid-tamper"
make_repo "$REPO3B"
node "$RUNTIME_CLI" install "$REPO3B" "$PLUGIN_ROOT" >/dev/null
helper="$REPO3B/.edc/hooks/lib/worker-manifest.mjs"
{
  head -1 "$helper"
  printf "import { writeFileSync as edcMarkerWrite } from 'node:fs'; edcMarkerWrite(process.env.EDC_TAMPER_MARKER, 'executed');\n"
  tail -n +2 "$helper"
} >"$TMP/tampered-helper.mjs"
mv "$TMP/tampered-helper.mjs" "$helper"
chmod +x "$helper"
set +e
EDC_TAMPER_MARKER="$TMP/tamper-marker" node "$RUNTIME_CLI" preflight "$REPO3B" "$PLUGIN_ROOT" >"$TMP/valid-tamper.out" 2>&1
valid_tamper_rc=$?
set -e
if [ "$valid_tamper_rc" -ne 0 ] \
  && grep -q 'runtime-integrity-mismatch' "$TMP/valid-tamper.out" \
  && [ ! -e "$TMP/tamper-marker" ]; then
  check "valid managed-helper tamper fails before helper execution" "1"
else
  check "valid managed-helper tamper fails before helper execution" "0"
  cat "$TMP/valid-tamper.out"
fi

REPO3C="$TMP/build-mode-tamper"
make_repo "$REPO3C"
mkdir -p "$REPO3C/src"
printf 'console.log("sample");\n' >"$REPO3C/src/app.js"
git -C "$REPO3C" add src/app.js
git -C "$REPO3C" commit -qm app
node "$RUNTIME_CLI" install "$REPO3C" "$PLUGIN_ROOT" >/dev/null
json_helper="$REPO3C/.edc/hooks/lib/json-cli.mjs"
{
  head -1 "$json_helper"
  printf "import { writeFileSync as edcMarkerWrite } from 'node:fs'; if (process.env.EDC_TAMPER_MARKER) edcMarkerWrite(process.env.EDC_TAMPER_MARKER, 'executed');\n"
  tail -n +2 "$json_helper"
} >"$TMP/tampered-json-cli.mjs"
mv "$TMP/tampered-json-cli.mjs" "$json_helper"
chmod +x "$json_helper"
set +e
(
  cd "$REPO3C"
  EDC_PLUGIN_ROOT="$PLUGIN_ROOT" \
    EDC_TAMPER_MARKER="$TMP/build-mode-tamper-marker" \
    EDC_REVIEW_TASKS_DIR="$TMP/build-mode-tasks" \
    EDC_REVIEW_TASKS_MANIFEST="$TMP/build-mode-tasks/manifest.json" \
    bash .edc/scripts/edc-review.sh --build --full --ignore-context
) >"$TMP/build-mode-tamper.out" 2>&1
build_mode_tamper_rc=$?
set -e
if [ "$build_mode_tamper_rc" -ne 0 ] \
  && grep -q 'runtime-integrity-mismatch' "$TMP/build-mode-tamper.out" \
  && [ ! -e "$TMP/build-mode-tamper-marker" ]; then
  check "review task build rejects a valid helper tamper before execution" "1"
else
  check "review task build rejects a valid helper tamper before execution" "0"
  cat "$TMP/build-mode-tamper.out"
fi

rm -f "$TMP/auto-tamper-marker" "$TMP/auto-tamper-result.json"
set +e
(
  cd "$REPO3C"
  PATH="$TMP/bin:$PATH" \
    EDC_PLUGIN_ROOT="$PLUGIN_ROOT" \
    EDC_AGENT_CLI=claude \
    EDC_RESULT_FILE="$TMP/auto-tamper-result.json" \
    EDC_TAMPER_MARKER="$TMP/auto-tamper-marker" \
    bash .edc/scripts/edc-review.sh --full --ignore-context
) >"$TMP/auto-tamper.out" 2>&1
exit_code=$?
set -e
if [ "$exit_code" -ne 0 ] \
  && grep -q 'runtime-integrity-mismatch' "$TMP/auto-tamper.out" \
  && [ ! -e "$TMP/auto-tamper-marker" ] \
  && node -e 'const j=require(process.argv[1]); process.exit(j.reasonCode === "runtime-integrity-mismatch" && j.status === "failed" ? 0 : 1)' "$TMP/auto-tamper-result.json"; then
  check "runtime mismatch writes failure result without executing tampered helper" "1"
else
  check "runtime mismatch writes failure result without executing tampered helper" "0"
  cat "$TMP/auto-tamper.out"
fi

tamper_sourced_helper() {
  local helper="$1" output="$2"
  {
    head -1 "$helper"
    printf '[ -n "${EDC_TAMPER_MARKER:-}" ] && printf executed > "$EDC_TAMPER_MARKER"\n'
    tail -n +2 "$helper"
  } >"$output"
  mv "$output" "$helper"
  chmod +x "$helper"
}

REPO3D="$TMP/audit-source-tamper"
make_repo "$REPO3D"
node "$RUNTIME_CLI" install "$REPO3D" "$PLUGIN_ROOT" >/dev/null
tamper_sourced_helper "$REPO3D/.edc/scripts/edc-assert-fresh.sh" "$TMP/tampered-audit-assert.sh"
set +e
(
  cd "$REPO3D"
  PATH="$TMP/bin:$PATH" \
    EDC_PLUGIN_ROOT="$PLUGIN_ROOT" \
    EDC_AGENT_CLI=claude \
    EDC_RESULT_FILE="$TMP/audit-tamper-result.json" \
    EDC_TAMPER_MARKER="$TMP/audit-tamper-marker" \
    bash .edc/scripts/edc-audit.sh
) >"$TMP/audit-tamper.out" 2>&1
audit_tamper_rc=$?
set -e
if [ "$audit_tamper_rc" -ne 0 ] \
  && grep -q 'runtime-integrity-mismatch' "$TMP/audit-tamper.out" \
  && [ ! -e "$TMP/audit-tamper-marker" ] \
  && node -e 'const j=require(process.argv[1]); process.exit(j.reasonCode === "runtime-integrity-mismatch" && j.kind === "audit" ? 0 : 1)' "$TMP/audit-tamper-result.json"; then
  check "quality review rejects sourced-helper tamper before execution" "1"
else
  check "quality review rejects sourced-helper tamper before execution" "0"
  cat "$TMP/audit-tamper.out"
fi

REPO3E="$TMP/delivery-source-tamper"
make_repo "$REPO3E"
node "$RUNTIME_CLI" install "$REPO3E" "$PLUGIN_ROOT" >/dev/null
tamper_sourced_helper "$REPO3E/.edc/scripts/edc-recover-context.sh" "$TMP/tampered-delivery-recover.sh"
set +e
(
  cd "$REPO3E"
  PATH="$TMP/bin:$PATH" \
    EDC_PLUGIN_ROOT="$PLUGIN_ROOT" \
    EDC_AGENT_CLI=claude \
    EDC_RESULT_FILE="$TMP/delivery-tamper-result.json" \
    EDC_TAMPER_MARKER="$TMP/delivery-tamper-marker" \
    bash .edc/scripts/edc-delivery-review.sh --full
) >"$TMP/delivery-tamper.out" 2>&1
delivery_tamper_rc=$?
set -e
if [ "$delivery_tamper_rc" -ne 0 ] \
  && grep -q 'runtime-integrity-mismatch' "$TMP/delivery-tamper.out" \
  && [ ! -e "$TMP/delivery-tamper-marker" ] \
  && node -e 'const j=require(process.argv[1]); process.exit(j.reasonCode === "runtime-integrity-mismatch" && j.kind === "delivery-review" ? 0 : 1)' "$TMP/delivery-tamper-result.json"; then
  check "delivery review rejects sourced-helper tamper before execution" "1"
else
  check "delivery review rejects sourced-helper tamper before execution" "0"
  cat "$TMP/delivery-tamper.out"
fi

REPO4="$TMP/interrupted"
make_repo "$REPO4"
node "$RUNTIME_CLI" install "$REPO4" "$PLUGIN_ROOT" >/dev/null
printf 'keep-me\n' >"$REPO4/.edc/config"
old_meta=$(shasum -a 256 "$REPO4/.edc/runtime-metadata.json" | awk '{print $1}')
set +e
EDC_RUNTIME_FAIL_AFTER_STAGE=1 node "$RUNTIME_CLI" install "$REPO4" "$PLUGIN_ROOT" >"$TMP/interrupted.out" 2>&1
interrupted_rc=$?
set -e
new_meta=$(shasum -a 256 "$REPO4/.edc/runtime-metadata.json" | awk '{print $1}')
if [ "$interrupted_rc" -ne 0 ] \
  && [ "$old_meta" = "$new_meta" ] \
  && grep -q 'keep-me' "$REPO4/.edc/config"; then
  check "interrupted promotion keeps previous valid runtime and config" "1"
else
  check "interrupted promotion keeps previous valid runtime and config" "0"
  cat "$TMP/interrupted.out"
fi

REPO5="$TMP/locked"
make_repo "$REPO5"
node "$RUNTIME_CLI" install "$REPO5" "$PLUGIN_ROOT" >/dev/null
rm -f "$REPO5/.edc/hooks/lib/worker-manifest.mjs"
mkdir "$REPO5/.edc.install.lock"
if ! node "$RUNTIME_CLI" preflight "$REPO5" "$PLUGIN_ROOT" --repair >"$TMP/locked.out" 2>&1 \
  && grep -q 'runtime-install-busy' "$TMP/locked.out"; then
  check "runtime repair reports lock contention as structured busy reason" "1"
else
  check "runtime repair reports lock contention as structured busy reason" "0"
  cat "$TMP/locked.out"
fi

REPO5A="$TMP/live-stale-lock"
make_repo "$REPO5A"
mkdir "$REPO5A/.edc.install.lock"
printf '{"pid":%s,"token":"live-owner","startedAt":"1970-01-01T00:00:00Z"}\n' "$$" >"$REPO5A/.edc.install.lock/owner.json"
touch -t 197001010000 "$REPO5A/.edc.install.lock" "$REPO5A/.edc.install.lock/owner.json"
if ! EDC_RUNTIME_LOCK_STALE_MS=1 node "$RUNTIME_CLI" install "$REPO5A" "$PLUGIN_ROOT" >"$TMP/live-stale-lock.out" 2>&1 \
  && grep -q 'runtime-install-busy' "$TMP/live-stale-lock.out" \
  && [ -f "$REPO5A/.edc.install.lock/owner.json" ]; then
  check "stale-looking lock remains busy while its owner is alive" "1"
else
  check "stale-looking lock remains busy while its owner is alive" "0"
  cat "$TMP/live-stale-lock.out"
fi
rm -rf "$REPO5A/.edc.install.lock"

REPO5R="$TMP/replaced-lock"
make_repo "$REPO5R"
set +e
EDC_RUNTIME_FAIL_AFTER_STAGE=1 node "$RUNTIME_CLI" install "$REPO5R" "$PLUGIN_ROOT" >"$TMP/replaced-lock.out" 2>&1 &
install_pid=$!
set -e
for _ in $(seq 1 500); do
  [ -f "$REPO5R/.edc.install.lock/owner.json" ] && break
  sleep 0.01
done
if [ -f "$REPO5R/.edc.install.lock/owner.json" ]; then
  rm -rf "$REPO5R/.edc.install.lock"
  mkdir "$REPO5R/.edc.install.lock"
  printf '{"pid":%s,"token":"replacement-owner","startedAt":"now"}\n' "$$" >"$REPO5R/.edc.install.lock/owner.json"
fi
wait "$install_pid" || true
if [ -f "$REPO5R/.edc.install.lock/owner.json" ] \
  && grep -q 'replacement-owner' "$REPO5R/.edc.install.lock/owner.json"; then
  check "installer release does not remove a replacement owner's lock" "1"
else
  check "installer release does not remove a replacement owner's lock" "0"
  cat "$TMP/replaced-lock.out"
fi
rm -rf "$REPO5R/.edc.install.lock"

REPO5B="$TMP/wrong-fingerprint"
make_repo "$REPO5B"
node "$RUNTIME_CLI" install "$REPO5B" "$PLUGIN_ROOT" >/dev/null
node -e 'const fs=require("fs"); const p=process.argv[1]; const j=JSON.parse(fs.readFileSync(p,"utf8")); j.fingerprint="wrong"; fs.writeFileSync(p, JSON.stringify(j));' "$REPO5B/.edc/runtime-metadata.json"
if ! node "$RUNTIME_CLI" preflight "$REPO5B" "$PLUGIN_ROOT" >"$TMP/wrong-fingerprint.out" 2>&1 \
  && grep -q 'runtime-version-mismatch' "$TMP/wrong-fingerprint.out"; then
  check "wrong runtime fingerprint returns structured version mismatch" "1"
else
  check "wrong runtime fingerprint returns structured version mismatch" "0"
  cat "$TMP/wrong-fingerprint.out"
fi

REPO6="$TMP/smoke"
make_repo "$REPO6"
node "$RUNTIME_CLI" install "$REPO6" "$PLUGIN_ROOT" >/dev/null
if node "$RUNTIME_CLI" preflight "$REPO6" >/"$TMP/smoke.out" 2>&1 \
  && grep -q '"reasonCode":"success"' "$TMP/smoke.out"; then
  check "runtime doctor performs worker-manifest smoke" "1"
else
  check "runtime doctor performs worker-manifest smoke" "0"
  cat "$TMP/smoke.out"
fi

check_summary "T48"
