#!/usr/bin/env bash
# Runtime robustness: canonical inventory, transactional install, preflight, and structured reasons.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
. "$ROOT/tests/hardening/lib/check.sh"
check_init

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"; check_cleanup' EXIT

PLUGIN_ROOT="$ROOT/plugins/edc"
RUNTIME_CLI="$PLUGIN_ROOT/hooks/lib/runtime-manifest.mjs"

install_global() {
  local home="$1" source="$2"
  mkdir -p "$home"
  HOME="$home" node "$source/hooks/lib/runtime-manifest.mjs" install "$home" "$source"
}

make_repo() {
  local repo="$1"
  mkdir -p "$repo"
  git -C "$repo" init -q
  git -C "$repo" config user.email test@example.invalid
  git -C "$repo" config user.name test
  git -C "$repo" config commit.gpgsign false
  cat >"$repo/AGENTS.md" <<'EOF'
# Agent Instructions

This repo ships deep architectural context generated by EDC. Read this file at session start before touching code.
EOF
  mkdir -p "$repo/edc-context/modules" "$repo/edc-context/reports" "$repo/edc-context/build"
  cat >"$repo/edc-context/index.md" <<'EOF'
# EDC context index
## Module table
EOF
  cat >"$repo/edc-context/manifest.json" <<'EOF'
{
  "schemaVersion": 2,
  "edcVersion": "test",
  "repoContextFile": "edc-context/index.md",
  "reports": { "issues": "edc-context/reports/issues.md", "complexity": "edc-context/reports/complexity.md" },
  "build": { "buildInfoFile": "edc-context/build/build.json" },
  "policy": { "defaultMode": "advisory", "unmatchedPathPolicy": "warn-allow" },
  "modules": [
    { "name": "sample", "doc": "edc-context/modules/sample.md", "priority": 100, "match": { "prefixes": ["src/"] } }
  ],
  "unmapped": { "allowedGlobs": [] },
  "coverage": { "ignoreGlobs": [] },
  "sourceCommit": "test"
}
EOF
  cat >"$repo/edc-context/modules/sample.md" <<'EOF'
# sample
## Scope
EOF
  git -C "$repo" add AGENTS.md edc-context
  git -C "$repo" commit -qm init
}

if [ -x "$RUNTIME_CLI" ] && node "$RUNTIME_CLI" inventory-check "$PLUGIN_ROOT" >/"$TMP/inventory.json" 2>"$TMP/inventory.err"; then
  check "canonical runtime inventory validates and sources exist" "1"
else
  check "canonical runtime inventory validates and sources exist" "0"
  cat "$TMP/inventory.err" 2>/dev/null || true
fi

EXPECTED_HOME="$TMP/expected-home"
NON_HOME_TARGET="$TMP/non-home-target"
mkdir -p "$EXPECTED_HOME" "$NON_HOME_TARGET"
set +e
HOME="$EXPECTED_HOME" node "$RUNTIME_CLI" install "$NON_HOME_TARGET" "$PLUGIN_ROOT" >"$TMP/non-home-install.out" 2>&1
non_home_install_rc=$?
set -e
if [ "$non_home_install_rc" -ne 0 ] \
  && grep -q 'runtime install target must be the current HOME' "$TMP/non-home-install.out" \
  && [ ! -e "$NON_HOME_TARGET/.edc" ] \
  && [ ! -e "$NON_HOME_TARGET/.edc.install.lock" ]; then
  check "runtime installer rejects non-HOME target before creating state" "1"
else
  check "runtime installer rejects non-HOME target before creating state" "0"
  cat "$TMP/non-home-install.out"
fi

REPO1="$TMP/source-install"
make_repo "$REPO1"
if install_global "$REPO1" "$PLUGIN_ROOT" >/dev/null \
  && [ -x "$REPO1/.edc/scripts/edc-review.sh" ] \
  && [ -f "$REPO1/.edc/hooks/lib/worker-manifest.mjs" ] \
  && [ -f "$REPO1/.edc/runtime-metadata.json" ]; then
  check "explicit source install writes complete managed runtime and metadata" "1"
else
  check "explicit source install writes complete managed runtime and metadata" "0"
fi

PACK_HOME="$TMP/pack-home"
mkdir -p "$PACK_HOME"
if HOME="$PACK_HOME" CI=1 SHELL=/bin/zsh bash "$ROOT/install.sh" --agent claude --no-path >/"$TMP/pack-install.out" 2>&1 \
  && [ -x "$PACK_HOME/.edc/scripts/edc" ] \
  && [ -f "$PACK_HOME/.edc/hooks/lib/worker-manifest.mjs" ] \
  && [ -f "$PACK_HOME/.edc/runtime-metadata.json" ]; then
  check "terminal/package install consumes runtime inventory" "1"
else
  check "terminal/package install consumes runtime inventory" "0"
  cat "$TMP/pack-install.out"
fi

mkdir -p "$TMP/bin"
cat >"$TMP/bin/claude" <<'EOF'
#!/usr/bin/env bash
echo called >>"${FAKE_MODEL_CALLED:?}"
exit 0
EOF
chmod +x "$TMP/bin/claude"

REPO3="$TMP/corrupt-helper"
make_repo "$REPO3"
install_global "$REPO3" "$PLUGIN_ROOT" >/dev/null
printf 'export const = broken\n' >"$REPO3/.edc/hooks/lib/worker-manifest.mjs"
if ! HOME="$REPO3" node "$RUNTIME_CLI" source-preflight "$REPO3/.edc" >/"$TMP/corrupt.out" 2>&1 \
  && grep -Eq 'runtime-(integrity-mismatch|version-mismatch)' "$TMP/corrupt.out"; then
  check "corrupt helper returns structured integrity reason" "1"
else
  check "corrupt helper returns structured integrity reason" "0"
  cat "$TMP/corrupt.out"
fi

REPO3B="$TMP/valid-tamper"
make_repo "$REPO3B"
install_global "$REPO3B" "$PLUGIN_ROOT" >/dev/null
helper="$REPO3B/.edc/hooks/lib/worker-manifest.mjs"
{
  head -1 "$helper"
  printf "import { writeFileSync as edcMarkerWrite } from 'node:fs'; edcMarkerWrite(process.env.EDC_TAMPER_MARKER, 'executed');\n"
  tail -n +2 "$helper"
} >"$TMP/tampered-helper.mjs"
mv "$TMP/tampered-helper.mjs" "$helper"
chmod +x "$helper"
set +e
HOME="$REPO3B" EDC_TAMPER_MARKER="$TMP/tamper-marker" node "$RUNTIME_CLI" source-preflight "$REPO3B/.edc" >"$TMP/valid-tamper.out" 2>&1
valid_tamper_rc=$?
set -e
if [ "$valid_tamper_rc" -ne 0 ] \
  && grep -Eq 'runtime-(integrity-mismatch|version-mismatch)' "$TMP/valid-tamper.out" \
  && [ ! -e "$TMP/tamper-marker" ]; then
  check "valid managed-helper tamper fails before helper execution" "1"
else
  check "valid managed-helper tamper fails before helper execution" "0"
  cat "$TMP/valid-tamper.out"
fi

SOURCE_SYMLINK="$TMP/source-symlink"
cp -R "$PLUGIN_ROOT" "$SOURCE_SYMLINK"
rm "$SOURCE_SYMLINK/scripts/edc"
ln -s "$PLUGIN_ROOT/scripts/edc" "$SOURCE_SYMLINK/scripts/edc"
REPO_SOURCE_CHECK="$TMP/source-check"
make_repo "$REPO_SOURCE_CHECK"
mkdir "$REPO_SOURCE_CHECK/.edc.install.lock"
printf 'untouched\n' >"$REPO_SOURCE_CHECK/.edc.install.lock/sentinel"
set +e
install_global "$REPO_SOURCE_CHECK" "$SOURCE_SYMLINK" >"$TMP/source-symlink.out" 2>&1
source_symlink_rc=$?
set -e
if [ "$source_symlink_rc" -ne 0 ] \
  && grep -q 'runtime-install-incomplete' "$TMP/source-symlink.out" \
  && grep -q 'sourcePath' "$TMP/source-symlink.out" \
  && grep -q 'untouched' "$REPO_SOURCE_CHECK/.edc.install.lock/sentinel"; then
  check "symlink runtime source fails before lock acquisition" "1"
else
  check "symlink runtime source fails before lock acquisition" "0"
  cat "$TMP/source-symlink.out"
fi
rm -rf "$REPO_SOURCE_CHECK/.edc.install.lock"

REPO_UPGRADE="$TMP/upgrade-cleanup"
make_repo "$REPO_UPGRADE"
install_global "$REPO_UPGRADE" "$PLUGIN_ROOT" >/dev/null
printf 'keep-config\n' >"$REPO_UPGRADE/.edc/config"
printf 'remove-stale\n' >"$REPO_UPGRADE/.edc/stale-helper"
mkdir -p "$REPO_UPGRADE/.edc/obsolete"
printf 'remove-nested\n' >"$REPO_UPGRADE/.edc/obsolete/helper"
install_global "$REPO_UPGRADE" "$PLUGIN_ROOT" >/dev/null
if grep -q 'keep-config' "$REPO_UPGRADE/.edc/config" \
  && [ ! -e "$REPO_UPGRADE/.edc/stale-helper" ] \
  && [ ! -e "$REPO_UPGRADE/.edc/obsolete" ]; then
  check "runtime upgrade preserves only config outside the manifest" "1"
else
  check "runtime upgrade preserves only config outside the manifest" "0"
fi

REPO4="$TMP/interrupted"
make_repo "$REPO4"
install_global "$REPO4" "$PLUGIN_ROOT" >/dev/null
printf 'keep-me\n' >"$REPO4/.edc/config"
old_meta=$(shasum -a 256 "$REPO4/.edc/runtime-metadata.json" | awk '{print $1}')
set +e
EDC_RUNTIME_FAIL_AFTER_STAGE=1 install_global "$REPO4" "$PLUGIN_ROOT" >"$TMP/interrupted.out" 2>&1
interrupted_rc=$?
set -e
new_meta=$(shasum -a 256 "$REPO4/.edc/runtime-metadata.json" | awk '{print $1}')
if [ "$interrupted_rc" -ne 0 ] \
  && [ "$old_meta" = "$new_meta" ] \
  && grep -q 'keep-me' "$REPO4/.edc/config"; then
  check "interrupted promotion keeps previous valid runtime and config" "1"
else
  check "interrupted promotion keeps previous valid runtime and config" "0"
  cat "$TMP/interrupted.out"
fi

REPO4B="$TMP/pre-stage-allocation-failure"
make_repo "$REPO4B"
set +e
EDC_RUNTIME_FAIL_BEFORE_STAGE=1 install_global "$REPO4B" "$PLUGIN_ROOT" >"$TMP/pre-stage-fail.out" 2>&1
pre_stage_rc=$?
install_global "$REPO4B" "$PLUGIN_ROOT" >"$TMP/pre-stage-retry.out" 2>&1
pre_stage_retry_rc=$?
set -e
if [ "$pre_stage_rc" -ne 0 ] \
  && node -e 'const fs=require("node:fs"); const j=JSON.parse(fs.readFileSync(process.argv[1], "utf8")); process.exit(j.status === "failed" && j.reasonCode === "runtime-validation-failed" && j.details?.stage === "before-stage" ? 0 : 1)' "$TMP/pre-stage-fail.out" \
  && [ ! -e "$REPO4B/.edc.install.lock" ] \
  && [ "$pre_stage_retry_rc" -eq 0 ] \
  && [ -x "$REPO4B/.edc/scripts/edc" ]; then
  check "pre-stage install failure releases lock and immediate retry succeeds" "1"
else
  check "pre-stage install failure releases lock and immediate retry succeeds" "0"
  printf 'pre_stage_rc=%s retry_rc=%s lock=%s\n' \
    "$pre_stage_rc" "$pre_stage_retry_rc" "$([ -e "$REPO4B/.edc.install.lock" ] && echo present || echo absent)"
  cat "$TMP/pre-stage-fail.out" "$TMP/pre-stage-retry.out"
fi

REPO5A="$TMP/live-stale-lock"
make_repo "$REPO5A"
mkdir "$REPO5A/.edc.install.lock"
printf '{"pid":%s,"token":"live-owner","startedAt":"1970-01-01T00:00:00Z"}\n' "$$" >"$REPO5A/.edc.install.lock/owner.json"
touch -t 197001010000 "$REPO5A/.edc.install.lock" "$REPO5A/.edc.install.lock/owner.json"
if ! EDC_RUNTIME_LOCK_STALE_MS=1 install_global "$REPO5A" "$PLUGIN_ROOT" >"$TMP/live-stale-lock.out" 2>&1 \
  && grep -q 'runtime-install-busy' "$TMP/live-stale-lock.out" \
  && [ -f "$REPO5A/.edc.install.lock/owner.json" ]; then
  check "stale-looking lock remains busy while its owner is alive" "1"
else
  check "stale-looking lock remains busy while its owner is alive" "0"
  cat "$TMP/live-stale-lock.out"
fi
rm -rf "$REPO5A/.edc.install.lock"

REPO5R="$TMP/replaced-lock"
make_repo "$REPO5R"
set +e
EDC_RUNTIME_FAIL_AFTER_STAGE=1 install_global "$REPO5R" "$PLUGIN_ROOT" >"$TMP/replaced-lock.out" 2>&1 &
install_pid=$!
set -e
for _ in $(seq 1 500); do
  [ -f "$REPO5R/.edc.install.lock/owner.json" ] && break
  sleep 0.01
done
if [ -f "$REPO5R/.edc.install.lock/owner.json" ]; then
  rm -rf "$REPO5R/.edc.install.lock"
  mkdir "$REPO5R/.edc.install.lock"
  printf '{"pid":%s,"token":"replacement-owner","startedAt":"now"}\n' "$$" >"$REPO5R/.edc.install.lock/owner.json"
fi
wait "$install_pid" || true
if [ -f "$REPO5R/.edc.install.lock/owner.json" ] \
  && grep -q 'replacement-owner' "$REPO5R/.edc.install.lock/owner.json"; then
  check "installer release does not remove a replacement owner's lock" "1"
else
  check "installer release does not remove a replacement owner's lock" "0"
  cat "$TMP/replaced-lock.out"
fi
rm -rf "$REPO5R/.edc.install.lock"

REPO5B="$TMP/wrong-fingerprint"
make_repo "$REPO5B"
install_global "$REPO5B" "$PLUGIN_ROOT" >/dev/null
node -e 'const fs=require("fs"); const p=process.argv[1]; const j=JSON.parse(fs.readFileSync(p,"utf8")); j.fingerprint="wrong"; fs.writeFileSync(p, JSON.stringify(j));' "$REPO5B/.edc/runtime-metadata.json"
if ! HOME="$REPO5B" node "$RUNTIME_CLI" source-preflight "$REPO5B/.edc" >"$TMP/wrong-fingerprint.out" 2>&1 \
  && grep -q 'runtime-version-mismatch' "$TMP/wrong-fingerprint.out"; then
  check "wrong runtime fingerprint returns structured version mismatch" "1"
else
  check "wrong runtime fingerprint returns structured version mismatch" "0"
  cat "$TMP/wrong-fingerprint.out"
fi

REPO6="$TMP/smoke"
make_repo "$REPO6"
install_global "$REPO6" "$PLUGIN_ROOT" >/dev/null
if HOME="$REPO6" node "$RUNTIME_CLI" source-preflight "$REPO6/.edc" >/"$TMP/smoke.out" 2>&1 \
  && grep -q '"reasonCode":"success"' "$TMP/smoke.out"; then
  check "runtime doctor performs worker-manifest smoke" "1"
else
  check "runtime doctor performs worker-manifest smoke" "0"
  cat "$TMP/smoke.out"
fi
install_global "$EXPECTED_HOME" "$PLUGIN_ROOT" >/dev/null
set +e
HOME="$EXPECTED_HOME" node "$RUNTIME_CLI" source-preflight "$REPO6/.edc" >"$TMP/non-home-preflight.out" 2>&1
non_home_preflight_rc=$?
set -e
if [ "$non_home_preflight_rc" -ne 0 ] \
  && grep -q 'installed EDC runtime must be current HOME' "$TMP/non-home-preflight.out"; then
  check "source preflight rejects installed runtime outside current HOME" "1"
else
  check "source preflight rejects installed runtime outside current HOME" "0"
  cat "$TMP/non-home-preflight.out"
fi

extract_bash_block() {
  awk '/^```bash$/{capture=1; next} /^```$/{if (capture) exit} capture' "$1" >"$2"
}

write_malicious_local_build() {
  local repo="$1"
  mkdir -p "$repo/.edc/scripts"
  cat >"$repo/.edc/scripts/edc-build.sh" <<'EOF'
#!/usr/bin/env bash
printf 'local\n' >"${LOCAL_MARKER:?}"
EOF
  chmod +x "$repo/.edc/scripts/edc-build.sh"
}

WRAPPER_PLUGIN="$TMP/trusted-wrapper-plugin"
cp -R "$PLUGIN_ROOT" "$WRAPPER_PLUGIN"
cat >"$WRAPPER_PLUGIN/scripts/edc-build.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/edc-lib.sh"
printf '%s\n%s\n%s\n%s\n' "$0" "$*" "$PWD" "${TRUSTED_ENV_VALUE:-}" >"${TRUSTED_MARKER:?}"
EOF
chmod +x "$WRAPPER_PLUGIN/scripts/edc-build.sh"
WRAPPER_PLUGIN_PHYSICAL=$(cd "$WRAPPER_PLUGIN" && pwd -P)
mkdir -p "$WRAPPER_PLUGIN/.edc/scripts"
cat >"$WRAPPER_PLUGIN/.edc/scripts/edc-build.sh" <<'EOF'
#!/usr/bin/env bash
printf 'plugin-local-decoy\n' >"${PLUGIN_DECOY_MARKER:?}"
EOF
chmod +x "$WRAPPER_PLUGIN/.edc/scripts/edc-build.sh"
worker_helper="$WRAPPER_PLUGIN/hooks/lib/worker-manifest.mjs"
{
  head -1 "$worker_helper"
  cat <<'EOF'
import { existsSync as raceExists, writeFileSync as raceWrite } from "node:fs";
if (process.env.EDC_RACE_READY && process.env.EDC_RACE_RELEASE) {
  raceWrite(process.env.EDC_RACE_READY, "ready\n");
  while (!raceExists(process.env.EDC_RACE_RELEASE)) {
    await new Promise((resolve) => setTimeout(resolve, 10));
  }
}
EOF
  tail -n +2 "$worker_helper"
} >"$TMP/race-worker-manifest.mjs"
mv "$TMP/race-worker-manifest.mjs" "$worker_helper"
chmod +x "$worker_helper"
cat >"$WRAPPER_PLUGIN/scripts/edc-review-all.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/edc-lib.sh"
edc_runtime_preflight_or_exit
printf '%s\n%s\n%s\n' "$0" "$*" "$PWD" >"${TERMINAL_REVIEW_MARKER:?}"
EOF
chmod +x "$WRAPPER_PLUGIN/scripts/edc-review-all.sh"

TERMINAL_HOME="$TMP/terminal-home"
TERMINAL_REPO="$TMP/terminal-bootstrap"
mkdir -p "$TERMINAL_HOME"
TERMINAL_HOME_PHYSICAL=$(cd "$TERMINAL_HOME" && pwd -P)
make_repo "$TERMINAL_REPO"
install_global "$TERMINAL_HOME" "$WRAPPER_PLUGIN" >/dev/null
cp -R "$TERMINAL_HOME/.edc" "$TERMINAL_REPO/.edc"
cat >"$TERMINAL_REPO/.edc/scripts/edc-review-all.sh" <<'EOF'
#!/usr/bin/env bash
printf 'executed\n' >"${LOCAL_MARKER:?}"
EOF
chmod +x "$TERMINAL_REPO/.edc/scripts/edc-review-all.sh"
mkdir "$TERMINAL_REPO/.edc.install.lock"
printf '{"pid":%s,"token":"repo-local-decoy","startedAt":"1970-01-01T00:00:00Z"}\n' "$$" >"$TERMINAL_REPO/.edc.install.lock/owner.json"
repo_runtime_before=$(find "$TERMINAL_REPO/.edc" -type f | LC_ALL=C sort | while IFS= read -r path; do shasum -a 256 "$path"; done | shasum -a 256 | awk '{print $1}')
set +e
(
  cd "$TERMINAL_REPO"
  HOME="$TERMINAL_HOME" \
    PATH="$TMP/bin:$PATH" \
    EDC_BUILD_MODEL=t48-model \
    EDC_REVIEW_MODEL=t48-model \
    LOCAL_MARKER="$TMP/terminal-local-marker" \
    TERMINAL_REVIEW_MARKER="$TMP/terminal-review-marker" \
    "$TERMINAL_HOME/.edc/scripts/edc" review --agent claude --full
) >"$TMP/terminal-review.out" 2>&1
terminal_review_rc=$?
set -e
repo_runtime_after=$(find "$TERMINAL_REPO/.edc" -type f | LC_ALL=C sort | while IFS= read -r path; do shasum -a 256 "$path"; done | shasum -a 256 | awk '{print $1}')
if [ "$terminal_review_rc" -eq 0 ] \
  && [ -f "$TMP/terminal-review-marker" ] \
  && [ ! -e "$TMP/terminal-local-marker" ] \
  && [ "$repo_runtime_before" = "$repo_runtime_after" ] \
  && [ -f "$TERMINAL_REPO/.edc.install.lock/owner.json" ] \
  && [ "$(sed -n '1p' "$TMP/terminal-review-marker")" = "$TERMINAL_HOME_PHYSICAL/.edc/scripts/edc-review-all.sh" ] \
  && [ "$(sed -n '2p' "$TMP/terminal-review-marker")" = "--full" ] \
  && [ "$(sed -n '3p' "$TMP/terminal-review-marker")" = "$TERMINAL_REPO" ]; then
  check "terminal/Pi bootstrap ignores stale repo runtime and dispatches validated global source" "1"
else
  check "terminal/Pi bootstrap ignores stale repo runtime and dispatches validated global source" "0"
  printf 'terminal review rc=%s marker=%s local=%s before=%s after=%s\n' \
    "$terminal_review_rc" "$([ -e "$TMP/terminal-review-marker" ] && tr '\n' '|' <"$TMP/terminal-review-marker" || echo missing)" \
    "$([ -e "$TMP/terminal-local-marker" ] && echo executed || echo absent)" "$repo_runtime_before" "$repo_runtime_after"
  cat "$TMP/terminal-review.out"
fi

PACKAGE_REPO="$TMP/package-bootstrap"
make_repo "$PACKAGE_REPO"
set +e
(
  cd "$PACKAGE_REPO"
  EDC_PLUGIN_ROOT="$TERMINAL_REPO/.edc" \
    TRUSTED_ENV_VALUE="package-env" \
    TRUSTED_MARKER="$TMP/package-trusted-marker" \
    node "$WRAPPER_PLUGIN/hooks/lib/runtime-bootstrap.mjs" edc-build.sh --package-arg
) >"$TMP/package-bootstrap.out" 2>&1
package_bootstrap_rc=$?
set -e
if [ "$package_bootstrap_rc" -eq 0 ] \
  && [ -f "$TMP/package-trusted-marker" ] \
  && [ ! -e "$PACKAGE_REPO/.edc" ] \
  && [ "$(sed -n '1p' "$TMP/package-trusted-marker")" = "$WRAPPER_PLUGIN_PHYSICAL/scripts/edc-build.sh" ]; then
  check "package bootstrap ignores caller runtime root and dispatches without repo cache" "1"
else
  check "package bootstrap ignores caller runtime root and dispatches without repo cache" "0"
  cat "$TMP/package-bootstrap.out"
fi

LOCAL_BOOTSTRAP_REPO="$TMP/local-bootstrap-rejected"
LOCAL_BOOTSTRAP_HOME="$TMP/local-bootstrap-home"
make_repo "$LOCAL_BOOTSTRAP_REPO"
mkdir -p "$LOCAL_BOOTSTRAP_HOME" "$TMP/local-bootstrap-bin"
cp -R "$TERMINAL_HOME/.edc" "$LOCAL_BOOTSTRAP_REPO/.edc"
cat >"$TMP/local-bootstrap-bin/bash" <<'EOF'
#!/bin/sh
printf 'executed\n' >"${LOCAL_BOOTSTRAP_EXECUTED:?}"
EOF
chmod +x "$TMP/local-bootstrap-bin/bash"
set +e
(
  cd "$LOCAL_BOOTSTRAP_REPO"
  HOME="$LOCAL_BOOTSTRAP_HOME" \
    PATH="$TMP/local-bootstrap-bin:$PATH" \
    LOCAL_BOOTSTRAP_EXECUTED="$TMP/local-bootstrap-executed" \
    node "$LOCAL_BOOTSTRAP_REPO/.edc/hooks/lib/runtime-bootstrap.mjs" edc-build.sh
) >"$TMP/local-bootstrap.out" 2>&1
local_bootstrap_rc=$?
set -e
if [ "$local_bootstrap_rc" -ne 0 ] \
  && grep -q 'repo-local EDC runtime execution is unsupported' "$TMP/local-bootstrap.out" \
  && [ ! -e "$TMP/local-bootstrap-executed" ]; then
  check "bootstrap rejects valid repo-local runtime before shell dispatch" "1"
else
  check "bootstrap rejects valid repo-local runtime before shell dispatch" "0"
  cat "$TMP/local-bootstrap.out"
fi

SYMLINK_BOOTSTRAP_REPO="$TMP/symlink-bootstrap-rejected"
make_repo "$SYMLINK_BOOTSTRAP_REPO"
ln -s "$WRAPPER_PLUGIN" "$SYMLINK_BOOTSTRAP_REPO/.edc"
set +e
(
  cd "$SYMLINK_BOOTSTRAP_REPO"
  HOME="$LOCAL_BOOTSTRAP_HOME" \
    PATH="$TMP/local-bootstrap-bin:$PATH" \
    LOCAL_BOOTSTRAP_EXECUTED="$TMP/symlink-bootstrap-executed" \
    node "$SYMLINK_BOOTSTRAP_REPO/.edc/hooks/lib/runtime-bootstrap.mjs" edc-build.sh
) >"$TMP/symlink-bootstrap.out" 2>&1
symlink_bootstrap_rc=$?
set -e
if [ "$symlink_bootstrap_rc" -ne 0 ] \
  && grep -q 'repo-local EDC runtime execution is unsupported' "$TMP/symlink-bootstrap.out" \
  && [ ! -e "$TMP/symlink-bootstrap-executed" ]; then
  check "bootstrap rejects repo-local symlink to package source" "1"
else
  check "bootstrap rejects repo-local symlink to package source" "0"
  cat "$TMP/symlink-bootstrap.out"
fi

GLOBAL_TAMPER_HOME="$TMP/global-tamper-home"
mkdir -p "$GLOBAL_TAMPER_HOME"
install_global "$GLOBAL_TAMPER_HOME" "$WRAPPER_PLUGIN" >/dev/null
global_worker="$GLOBAL_TAMPER_HOME/.edc/hooks/lib/worker-manifest.mjs"
{
  head -1 "$global_worker"
  printf "import { writeFileSync as markTamper } from 'node:fs'; markTamper(process.env.GLOBAL_TAMPER_MARKER, 'executed');\n"
  tail -n +2 "$global_worker"
} >"$TMP/global-worker-tamper.mjs"
mv "$TMP/global-worker-tamper.mjs" "$global_worker"
chmod +x "$global_worker"
set +e
HOME="$GLOBAL_TAMPER_HOME" \
  GLOBAL_TAMPER_MARKER="$TMP/global-tamper-marker" \
  node "$GLOBAL_TAMPER_HOME/.edc/hooks/lib/runtime-bootstrap.mjs" edc-build.sh >"$TMP/global-tamper.out" 2>&1
global_tamper_rc=$?
set -e
if [ "$global_tamper_rc" -ne 0 ] \
  && grep -Eq 'runtime-(integrity-mismatch|version-mismatch)' "$TMP/global-tamper.out" \
  && [ ! -e "$TMP/global-tamper-marker" ]; then
  check "direct managed global-source tamper fails closed before helper execution" "1"
else
  check "direct managed global-source tamper fails closed before helper execution" "0"
  cat "$TMP/global-tamper.out"
fi

RACE_REPO="$TMP/runtime-use-race"
make_repo "$RACE_REPO"
mkdir -p "$RACE_REPO/.edc/scripts"
set +e
(
  cd "$RACE_REPO"
  EDC_RACE_READY="$TMP/race-ready" \
    EDC_RACE_RELEASE="$TMP/race-release" \
    TRUSTED_ENV_VALUE="trusted-env" \
    TRUSTED_MARKER="$TMP/race-trusted-marker" \
    node "$WRAPPER_PLUGIN/hooks/lib/runtime-bootstrap.mjs" edc-build.sh --race-arg
) >"$TMP/race-bootstrap.out" 2>&1 &
race_bootstrap_pid=$!
set -e
for _ in $(seq 1 500); do
  [ -f "$TMP/race-ready" ] && break
  sleep 0.01
done
cat >"$RACE_REPO/.edc/scripts/edc-lib.sh" <<EOF
printf 'raced-local-helper\n' >"$TMP/race-local-helper-marker"
EOF
cat >"$RACE_REPO/.edc/scripts/edc-build.sh" <<EOF
#!/usr/bin/env bash
. "\$(dirname "\${BASH_SOURCE[0]}")/edc-lib.sh"
printf 'raced-local-top\n' >"$TMP/race-local-top-marker"
EOF
chmod +x "$RACE_REPO/.edc/scripts/edc-build.sh"
touch "$TMP/race-release"
set +e
wait "$race_bootstrap_pid"
race_bootstrap_rc=$?
set -e
if [ "$race_bootstrap_rc" -eq 0 ] \
  && [ -f "$TMP/race-trusted-marker" ] \
  && [ ! -e "$TMP/race-local-top-marker" ] \
  && [ ! -e "$TMP/race-local-helper-marker" ] \
  && [ "$(sed -n '1p' "$TMP/race-trusted-marker")" = "$WRAPPER_PLUGIN_PHYSICAL/scripts/edc-build.sh" ] \
  && [ "$(sed -n '2p' "$TMP/race-trusted-marker")" = "--race-arg" ] \
  && [ "$(sed -n '3p' "$TMP/race-trusted-marker")" = "$RACE_REPO" ] \
  && [ "$(sed -n '4p' "$TMP/race-trusted-marker")" = "trusted-env" ]; then
  check "trusted bootstrap resists post-validation top-level and sourced-helper swaps" "1"
else
  check "trusted bootstrap resists post-validation top-level and sourced-helper swaps" "0"
  printf 'race rc=%s local_top=%s local_helper=%s trusted=%s\n' \
    "$race_bootstrap_rc" "$([ -e "$TMP/race-local-top-marker" ] && echo yes || echo no)" \
    "$([ -e "$TMP/race-local-helper-marker" ] && echo yes || echo no)" \
    "$([ -e "$TMP/race-trusted-marker" ] && tr '\n' '|' <"$TMP/race-trusted-marker" || echo missing)"
  cat "$TMP/race-bootstrap.out"
fi

CANCEL_PLUGIN="$TMP/trusted-cancel-plugin"
cp -R "$WRAPPER_PLUGIN" "$CANCEL_PLUGIN"
cat >"$CANCEL_PLUGIN/scripts/edc-build.sh" <<'EOF'
#!/usr/bin/env bash
exec node -e 'const fs = require("node:fs"); fs.writeFileSync(process.env.CANCEL_STARTED, "started\n"); setTimeout(() => fs.writeFileSync(process.env.CANCEL_SURVIVED, "survived\n"), 1500);'
EOF
cat >"$CANCEL_PLUGIN/scripts/edc-update.sh" <<'EOF'
#!/usr/bin/env bash
node -e 'const fs = require("node:fs"); fs.writeFileSync(process.env.NESTED_CANCEL_PID, `${process.pid}\n`); fs.writeFileSync(process.env.NESTED_CANCEL_STARTED, "started\n"); setTimeout(() => fs.writeFileSync(process.env.NESTED_CANCEL_SURVIVED, "survived\n"), 1500); setInterval(() => {}, 1000);'
EOF
chmod +x "$CANCEL_PLUGIN/scripts/edc-build.sh" "$CANCEL_PLUGIN/scripts/edc-update.sh"
CANCEL_REPO="$TMP/bootstrap-cancel"
make_repo "$CANCEL_REPO"

run_cancel_case() {
  local signal="$1" expected_rc="$2" suffix
  suffix=$(printf '%s' "$signal" | tr '[:upper:]' '[:lower:]')
  local started="$TMP/cancel-$suffix-started"
  local survived="$TMP/cancel-$suffix-survived"
  local output="$TMP/cancel-$suffix-bootstrap.out"
  set +e
  (
    cd "$CANCEL_REPO"
    CANCEL_STARTED="$started" \
      CANCEL_SURVIVED="$survived" \
      exec node "$CANCEL_PLUGIN/hooks/lib/runtime-bootstrap.mjs" edc-build.sh
  ) >"$output" 2>&1 &
  cancel_bootstrap_pid=$!
  set -e
  for _ in $(seq 1 500); do
    [ -f "$started" ] && break
    sleep 0.01
  done
  kill -"$signal" "$cancel_bootstrap_pid"
  set +e
  wait "$cancel_bootstrap_pid"
  cancel_bootstrap_rc=$?
  set -e
  sleep 2
  if [ "$cancel_bootstrap_rc" -eq "$expected_rc" ] \
    && [ -f "$started" ] \
    && [ ! -e "$survived" ]; then
    check "trusted bootstrap forwards $signal and preserves signal exit $expected_rc" "1"
  else
    check "trusted bootstrap forwards $signal and preserves signal exit $expected_rc" "0"
    printf 'cancel signal=%s rc=%s started=%s survived=%s\n' \
      "$signal" "$cancel_bootstrap_rc" "$([ -e "$started" ] && echo yes || echo no)" \
      "$([ -e "$survived" ] && echo yes || echo no)"
    cat "$output"
  fi
}

run_cancel_case TERM 143
run_cancel_case INT 130
run_cancel_case HUP 129

CANCEL_HOME="$TMP/terminal-cancel-home"
mkdir -p "$CANCEL_HOME"
install_global "$CANCEL_HOME" "$CANCEL_PLUGIN" >/dev/null
set +e
HOME="$CANCEL_HOME" \
  PATH="$TMP/bin:$PATH" \
  EDC_BUILD_MODEL=t48-model \
  EDC_REVIEW_MODEL=t48-model \
  CANCEL_STARTED="$TMP/terminal-cancel-started" \
  CANCEL_SURVIVED="$TMP/terminal-cancel-survived" \
  "$CANCEL_HOME/.edc/scripts/edc" build --agent claude "$CANCEL_REPO" >"$TMP/terminal-cancel.out" 2>&1 &
terminal_cancel_pid=$!
set -e
for _ in $(seq 1 500); do
  [ -f "$TMP/terminal-cancel-started" ] && break
  sleep 0.01
done
kill -TERM "$terminal_cancel_pid"
set +e
wait "$terminal_cancel_pid"
terminal_cancel_rc=$?
set -e
sleep 2
if [ "$terminal_cancel_rc" -eq 143 ] \
  && [ -f "$TMP/terminal-cancel-started" ] \
  && [ ! -e "$TMP/terminal-cancel-survived" ]; then
  check "terminal cli execs bootstrap so TERM reaches the orchestrator" "1"
else
  check "terminal cli execs bootstrap so TERM reaches the orchestrator" "0"
  printf 'terminal cancel rc=%s started=%s survived=%s\n' \
    "$terminal_cancel_rc" "$([ -e "$TMP/terminal-cancel-started" ] && echo yes || echo no)" \
    "$([ -e "$TMP/terminal-cancel-survived" ] && echo yes || echo no)"
  cat "$TMP/terminal-cancel.out"
fi

set +e
(
  cd "$CANCEL_REPO"
  HOME="$CANCEL_HOME" \
    PATH="$TMP/bin:$PATH" \
    EDC_BUILD_MODEL=t48-model \
    EDC_REVIEW_MODEL=t48-model \
    NESTED_CANCEL_PID="$TMP/nested-cancel-pid" \
    NESTED_CANCEL_STARTED="$TMP/nested-cancel-started" \
    NESTED_CANCEL_SURVIVED="$TMP/nested-cancel-survived" \
    exec "$CANCEL_HOME/.edc/scripts/edc" update --agent claude
) >"$TMP/nested-cancel.out" 2>&1 &
nested_cancel_cli_pid=$!
set -e
for _ in $(seq 1 500); do
  [ -f "$TMP/nested-cancel-started" ] && break
  sleep 0.01
done
kill -TERM "$nested_cancel_cli_pid"
for _ in $(seq 1 500); do
  kill -0 "$nested_cancel_cli_pid" 2>/dev/null || break
  sleep 0.01
done
if kill -0 "$nested_cancel_cli_pid" 2>/dev/null; then
  kill -KILL "$nested_cancel_cli_pid" 2>/dev/null || true
fi
set +e
wait "$nested_cancel_cli_pid"
nested_cancel_cli_rc=$?
set -e
sleep 2
nested_cancel_descendant_pid=$(cat "$TMP/nested-cancel-pid" 2>/dev/null || true)
nested_cancel_descendant_alive=0
if [ -n "$nested_cancel_descendant_pid" ] && kill -0 "$nested_cancel_descendant_pid" 2>/dev/null; then
  nested_cancel_descendant_alive=1
fi
if [ "$nested_cancel_cli_rc" -eq 143 ] \
  && [ -f "$TMP/nested-cancel-started" ] \
  && [ ! -e "$TMP/nested-cancel-survived" ] \
  && [ "$nested_cancel_descendant_alive" -eq 0 ]; then
  check "terminal cli TERM cancels non-exec nested orchestrator descendants" "1"
else
  check "terminal cli TERM cancels non-exec nested orchestrator descendants" "0"
  printf 'nested cancel rc=%s started=%s survived=%s descendant_pid=%s descendant_alive=%s\n' \
    "$nested_cancel_cli_rc" "$([ -e "$TMP/nested-cancel-started" ] && echo yes || echo no)" \
    "$([ -e "$TMP/nested-cancel-survived" ] && echo yes || echo no)" \
    "${nested_cancel_descendant_pid:-missing}" "$nested_cancel_descendant_alive"
  cat "$TMP/nested-cancel.out"
fi
if [ "$nested_cancel_descendant_alive" -eq 1 ]; then
  kill -KILL "$nested_cancel_descendant_pid" 2>/dev/null || true
fi

STATIC_REPO="$TMP/static-wrapper"
make_repo "$STATIC_REPO"
write_malicious_local_build "$STATIC_REPO"
extract_bash_block "$ROOT/plugins/edc/commands/edc-build.md" "$TMP/static-wrapper.sh"
set +e
(
  cd "$STATIC_REPO"
  ARGUMENTS='--force' \
    CLAUDE_PLUGIN_ROOT="$WRAPPER_PLUGIN" \
    LOCAL_MARKER="$TMP/static-local-marker" \
    PLUGIN_DECOY_MARKER="$TMP/static-plugin-decoy-marker" \
    TRUSTED_ENV_VALUE="static-env" \
    TRUSTED_MARKER="$TMP/static-trusted-marker" \
    bash "$TMP/static-wrapper.sh"
) >"$TMP/static-wrapper.out" 2>&1
static_wrapper_rc=$?
set -e
if [ "$static_wrapper_rc" -eq 0 ] \
  && [ -f "$TMP/static-trusted-marker" ] \
  && [ ! -e "$TMP/static-local-marker" ] \
  && [ ! -e "$TMP/static-plugin-decoy-marker" ] \
  && [ "$(sed -n '1p' "$TMP/static-trusted-marker")" = "$WRAPPER_PLUGIN_PHYSICAL/scripts/edc-build.sh" ] \
  && [ "$(sed -n '2p' "$TMP/static-trusted-marker")" = "--force" ] \
  && [ "$(sed -n '3p' "$TMP/static-trusted-marker")" = "$STATIC_REPO" ] \
  && [ "$(sed -n '4p' "$TMP/static-trusted-marker")" = "static-env" ]; then
  check "static Claude wrapper validates package source and ignores repo runtime" "1"
else
  check "static Claude wrapper validates package source and ignores repo runtime" "0"
  cat "$TMP/static-wrapper.out"
fi

GENERATED_HOME="$TMP/generated-home"
mkdir -p "$GENERATED_HOME"
GENERATED_HOME_PHYSICAL=$(cd "$GENERATED_HOME" && pwd -P)
HOME="$GENERATED_HOME" CI=1 SHELL=/bin/zsh bash "$ROOT/install.sh" --agent cursor --no-path >"$TMP/generated-cursor-install.out" 2>&1
HOME="$GENERATED_HOME" CI=1 SHELL=/bin/zsh bash "$ROOT/install.sh" --agent codex --no-path >"$TMP/generated-codex-install.out" 2>&1
install_global "$GENERATED_HOME" "$WRAPPER_PLUGIN" >/dev/null
installed_shell_source_root=$(
  cd "$TMP"
  HOME="$GENERATED_HOME" EDC_SCRIPTS_DIR="$GENERATED_HOME/.edc/scripts" bash -c '. "$EDC_SCRIPTS_DIR/edc-lib.sh"; edc_runtime_source_root'
)
if [ "$installed_shell_source_root" = "$GENERATED_HOME_PHYSICAL/.edc" ]; then
  check "installed edc-lib reports the deterministic .edc source root" "1"
else
  check "installed edc-lib reports the deterministic .edc source root" "0"
  printf 'installed shell source root=%s\n' "$installed_shell_source_root"
fi
mkdir -p "$GENERATED_HOME/scripts" "$GENERATED_HOME/hooks/lib"
cat >"$GENERATED_HOME/scripts/edc-build.sh" <<'EOF'
#!/usr/bin/env bash
printf 'installed-decoy\n' >"${INSTALLED_DECOY_MARKER:?}"
EOF
chmod +x "$GENERATED_HOME/scripts/edc-build.sh"
cat >"$GENERATED_HOME/hooks/lib/worker-manifest.mjs" <<'EOF'
#!/usr/bin/env node
import { writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
writeFileSync(process.env.INSTALLED_HELPER_DECOY_MARKER, "installed-helper-decoy\n");
const child = spawnSync(process.execPath, [process.env.INSTALLED_REAL_WORKER, ...process.argv.slice(2)], { env: process.env, stdio: "inherit" });
process.exit(typeof child.status === "number" ? child.status : 1);
EOF
chmod +x "$GENERATED_HOME/hooks/lib/worker-manifest.mjs"

plugin_fingerprint=$(node "$WRAPPER_PLUGIN/hooks/lib/runtime-manifest.mjs" inventory-check "$WRAPPER_PLUGIN" | node -e 'let s=""; process.stdin.on("data",c=>s+=c).on("end",()=>process.stdout.write(JSON.parse(s).fingerprint));')
set +e
installed_fingerprint=$(node "$GENERATED_HOME/.edc/hooks/lib/runtime-manifest.mjs" inventory-check "$GENERATED_HOME/.edc" 2>"$TMP/installed-fingerprint.err" | node -e 'let s=""; process.stdin.on("data",c=>s+=c).on("end",()=>process.stdout.write(JSON.parse(s).fingerprint));')
installed_fingerprint_rc=$?
set -e
if [ "$installed_fingerprint_rc" -eq 0 ] && [ "$plugin_fingerprint" = "$installed_fingerprint" ]; then
  check "plugin and installed runtime layouts have fingerprint parity" "1"
else
  check "plugin and installed runtime layouts have fingerprint parity" "0"
  cat "$TMP/installed-fingerprint.err"
fi

CURSOR_REPO="$TMP/cursor-wrapper"
make_repo "$CURSOR_REPO"
write_malicious_local_build "$CURSOR_REPO"
extract_bash_block "$GENERATED_HOME/.cursor/commands/edc-build.md" "$TMP/cursor-wrapper.sh"
set +e
(
  cd "$CURSOR_REPO"
  HOME="$GENERATED_HOME" \
    ARGUMENTS='--cursor-arg' \
    LOCAL_MARKER="$TMP/cursor-local-marker" \
    INSTALLED_DECOY_MARKER="$TMP/cursor-installed-decoy-marker" \
    INSTALLED_HELPER_DECOY_MARKER="$TMP/cursor-installed-helper-decoy-marker" \
    INSTALLED_REAL_WORKER="$GENERATED_HOME/.edc/hooks/lib/worker-manifest.mjs" \
    TRUSTED_ENV_VALUE="cursor-env" \
    TRUSTED_MARKER="$TMP/cursor-trusted-marker" \
    bash "$TMP/cursor-wrapper.sh"
) >"$TMP/cursor-wrapper.out" 2>&1
cursor_wrapper_rc=$?
set -e
if [ "$cursor_wrapper_rc" -eq 0 ] \
  && [ -f "$TMP/cursor-trusted-marker" ] \
  && [ ! -e "$TMP/cursor-local-marker" ] \
  && [ ! -e "$TMP/cursor-installed-decoy-marker" ] \
  && [ ! -e "$TMP/cursor-installed-helper-decoy-marker" ] \
  && [ "$(sed -n '1p' "$TMP/cursor-trusted-marker")" = "$GENERATED_HOME_PHYSICAL/.edc/scripts/edc-build.sh" ] \
  && [ "$(sed -n '2p' "$TMP/cursor-trusted-marker")" = "--cursor-arg" ] \
  && [ "$(sed -n '3p' "$TMP/cursor-trusted-marker")" = "$CURSOR_REPO" ] \
  && [ "$(sed -n '4p' "$TMP/cursor-trusted-marker")" = "cursor-env" ]; then
  check "generated Cursor wrapper uses trusted HOME bootstrap and ignores repo runtime" "1"
else
  check "generated Cursor wrapper uses trusted HOME bootstrap and ignores repo runtime" "0"
  cat "$TMP/cursor-wrapper.out"
fi

CODEX_REPO="$TMP/codex-wrapper"
make_repo "$CODEX_REPO"
rm -f "$TMP/cursor-installed-decoy-marker" "$TMP/cursor-installed-helper-decoy-marker"
write_malicious_local_build "$CODEX_REPO"
extract_bash_block "$GENERATED_HOME/.codex/skills/edc-build/SKILL.md" "$TMP/codex-wrapper.sh"
set +e
(
  cd "$CODEX_REPO"
  HOME="$GENERATED_HOME" \
    LOCAL_MARKER="$TMP/codex-local-marker" \
    INSTALLED_DECOY_MARKER="$TMP/codex-installed-decoy-marker" \
    INSTALLED_HELPER_DECOY_MARKER="$TMP/codex-installed-helper-decoy-marker" \
    INSTALLED_REAL_WORKER="$GENERATED_HOME/.edc/hooks/lib/worker-manifest.mjs" \
    TRUSTED_ENV_VALUE="codex-env" \
    TRUSTED_MARKER="$TMP/codex-trusted-marker" \
    bash "$TMP/codex-wrapper.sh" --codex-arg
) >"$TMP/codex-wrapper.out" 2>&1
codex_wrapper_rc=$?
set -e
if [ "$codex_wrapper_rc" -eq 0 ] \
  && [ -f "$TMP/codex-trusted-marker" ] \
  && [ ! -e "$TMP/codex-local-marker" ] \
  && [ ! -e "$TMP/codex-installed-decoy-marker" ] \
  && [ ! -e "$TMP/codex-installed-helper-decoy-marker" ] \
  && [ "$(sed -n '1p' "$TMP/codex-trusted-marker")" = "$GENERATED_HOME_PHYSICAL/.edc/scripts/edc-build.sh" ] \
  && [ "$(sed -n '2p' "$TMP/codex-trusted-marker")" = "--codex-arg" ] \
  && [ "$(sed -n '3p' "$TMP/codex-trusted-marker")" = "$CODEX_REPO" ] \
  && [ "$(sed -n '4p' "$TMP/codex-trusted-marker")" = "codex-env" ]; then
  check "generated Codex wrapper uses trusted HOME bootstrap and ignores repo runtime" "1"
else
  check "generated Codex wrapper uses trusted HOME bootstrap and ignores repo runtime" "0"
  cat "$TMP/codex-wrapper.out"
fi

check_summary "T48"
