#!/usr/bin/env bash
# Task 6 smoke test: end-to-end auto_mode pipeline with a mocked agent CLI.
#
# Catches regressions where the orchestrator can no longer spawn its agent
# subprocesses — the canonical example being the run_with_timeout-cannot-exec-
# shell-functions bug (see commit history around the run_agent removal).
#
# Strategy:
#   1. Build a fake "claude" binary on PATH that reads a prompt from stdin and
#      writes whatever artifact the orchestrator expects for that phase.
#   2. Set up a minimal git repo with pre-existing valid context.
#   3. Make a two-module committed change and run `edc-review.sh HEAD --base HEAD~1 --committed-only`.
#   4. Assert stale-context recovery updates from manifest.sourceCommit.
#   5. Assert a final review-*.md file is produced.
#
# Run from repo root: bash tests/hardening/t6-auto-mode.sh
set -euo pipefail


SCRIPT_REL="plugins/edc/scripts/edc-review.sh"
ORIG_DIR="$(pwd)"
SCRIPT="$ORIG_DIR/$SCRIPT_REL"
TMPDIR_T6=$(mktemp -d)
MOCK_BIN="$TMPDIR_T6/bin"
trap 'rm -rf "$TMPDIR_T6"' EXIT

echo "=== T6: end-to-end auto_mode pipeline (mocked agent) ==="

# ── build the mock agent ─────────────────────────────────────────────────────
mkdir -p "$MOCK_BIN"
cat > "$MOCK_BIN/claude" <<'MOCK'
#!/usr/bin/env bash
# Mock claude CLI for t6. Reads the prompt from stdin (here-string from the
# orchestrator) and writes the artifact the orchestrator expects for that phase.
#
# Recognized phases:
#   - prompt mentions "edc-build" → write valid edc-context/{index.md,manifest.json,modules/root.md}
#   - prompt mentions "edc-update" → refresh manifest.json:sourceCommit to HEAD
#   - prompt mentions "--task-file <path>" → write report-<module>.md with ## heading
#
# Always exits 0 with empty stdout (stream_filter handles empty input fine).
set -euo pipefail
prompt=$(cat)
previous=""
for arg in "$@"; do
  if [ "$previous" = "--system-prompt-file" ]; then
    prompt=$(cat "$arg")
    break
  fi
  previous="$arg"
done

# NOTE: prompt classification order matters. Review prompts embed methodology
# that can mention build/update concepts, so check TASK FILE first. The update
# skill content contains the string "edc-build" (it references the build flow),
# so check edc-update before edc-build.
if [[ "$prompt" == *"TASK FILE: "* ]]; then
  task_path=$(printf '%s' "$prompt" | grep -oE 'TASK FILE: [^ ]+' | head -1 | awk '{print $3}')
  if [ -z "$task_path" ]; then
    echo "MOCK ERROR: could not parse TASK FILE from prompt" >&2
    exit 1
  fi
  module=$(basename "$task_path" .md)
  task_dir=$(dirname "$task_path")
  mkdir -p "$task_dir"
  if [ "${REVIEW_PARALLEL_PROBE:-0}" = "1" ]; then
    mkdir -p "${REVIEW_PROBE_DIR:?}/active"
    : > "$REVIEW_PROBE_DIR/active/$module"
    active=$(find "$REVIEW_PROBE_DIR/active" -type f | wc -l | tr -d ' ')
    printf '%s\n' "$active" >> "$REVIEW_PROBE_DIR/overlap"
    sleep 0.4
    rm -f "$REVIEW_PROBE_DIR/active/$module"
  fi
  printf '## Findings\n\nMock review for module %s.\n' "$module" > "$task_dir/report-${module}.md"
  exit 0
fi

if [[ "$prompt" == *"edc-update-impl"* ]] || [[ "$prompt" == *"# Update Context (v2)"* ]]; then
  printf '%s' "$prompt" > .mock-update-prompt
  head=$(git rev-parse HEAD)
  # Naive in-place rewrite of sourceCommit. Adequate for test purposes.
  sed -i.bak 's/"sourceCommit":"[^"]*"/"sourceCommit":"'"$head"'"/' edc-context/manifest.json
  rm -f edc-context/manifest.json.bak
  exit 0
fi

if [[ "$prompt" == *"edc-build"* ]]; then
  mkdir -p edc-context/modules
  printf '<!-- generated by t6 mock -->\n# Stub Architecture\n\n## Module Map\n\n- root\n- second\n' > edc-context/index.md
  head=$(git rev-parse HEAD)
  printf '{"schemaVersion":2,"sourceCommit":"%s","policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"modules":[{"name":"root","doc":"edc-context/modules/root.md","priority":10,"match":{"exactFiles":["change.txt"]}},{"name":"second","doc":"edc-context/modules/second.md","priority":10,"match":{"exactFiles":["another.txt"]}}]}\n' "$head" > edc-context/manifest.json
  printf '<!-- generated by t6 mock -->\n# root\n\n## Files\n\n- change.txt\n' > edc-context/modules/root.md
  printf '<!-- generated by t6 mock -->\n# second\n\n## Files\n\n- another.txt\n' > edc-context/modules/second.md
  exit 0
fi

echo "MOCK ERROR: unrecognized prompt: $prompt" >&2
exit 1
MOCK
chmod +x "$MOCK_BIN/claude"

# ── set up a minimal git repo with valid pre-existing context ────────────────
cd "$TMPDIR_T6"
# Insulate from any host git config (gpg signing, hooks, etc.) that would
# otherwise make `git commit` block or fail. GIT_CONFIG_GLOBAL=/dev/null gives
# us a hermetic per-test git environment.
export GIT_CONFIG_GLOBAL=/dev/null
export GIT_CONFIG_SYSTEM=/dev/null
git init -q
git config user.email "test@test.com"
git config user.name "Test"
git config commit.gpgsign false
echo "initial" > seed.txt
git add seed.txt
git commit -q -m "init"

node "$ORIG_DIR/plugins/edc/hooks/lib/runtime-manifest.mjs" install "$TMPDIR_T6" "$ORIG_DIR/plugins/edc" >/dev/null

# Pre-populate valid context (already-fresh: lastCommit == HEAD-of-base, but we
# add another commit below and rely on auto_mode's CONTEXT_STALE → edc-update
# recovery to bring it forward). This is the realistic happy path.
mkdir -p edc-context/modules
base_head=$(git rev-parse HEAD)
printf '<!-- generated by t6 -->\n# Stub Architecture\n\n## Module Map\n\n- root\n- second\n' > edc-context/index.md
printf '{"schemaVersion":2,"sourceCommit":"%s","policy":{"defaultMode":"advisory","unmatchedPathPolicy":"warn-allow"},"modules":[{"name":"root","doc":"edc-context/modules/root.md","priority":10,"match":{"exactFiles":["change.txt"]}},{"name":"second","doc":"edc-context/modules/second.md","priority":10,"match":{"exactFiles":["another.txt"]}}]}\n' "$base_head" > edc-context/manifest.json
printf '<!-- generated by t6 -->\n# root\n\n## Files\n\n- change.txt\n' > edc-context/modules/root.md
printf '<!-- generated by t6 -->\n# second\n\n## Files\n\n- another.txt\n' > edc-context/modules/second.md

# Make real changes in two modules so bounded fanout can overlap.
echo "modified" > change.txt
echo "also modified" > another.txt
git add change.txt another.txt
git commit -q -m "add change"

# ── run the orchestrator with mocked claude on PATH ──────────────────────────
export PATH="$MOCK_BIN:$PATH"
export EDC_AGENT_CLI=claude

# Sanity: the mock is what gets resolved.
which_claude=$(command -v claude)
if [ "$which_claude" != "$MOCK_BIN/claude" ]; then
  echo "FAIL: mock claude not first on PATH (got $which_claude)"
  exit 1
fi
echo "→ using mock claude at: $which_claude"

# Run the full pipeline. The explicit review base must not replace the manifest
# sourceCommit used for context recovery. Capture output for diagnostics.
result=0
out=$(REVIEW_PARALLEL_PROBE=1 REVIEW_PROBE_DIR="$TMPDIR_T6/.git/probe" EDC_MAX_CONCURRENCY=2 EDC_KEEP_REVIEW_TASKS=1 bash "$SCRIPT" HEAD --base HEAD~1 --committed-only 2>&1) || result=$?

if [ "$result" -ne 0 ]; then
  echo "FAIL: orchestrator exited non-zero ($result)"
  echo "--- output ---"
  echo "$out"
  echo "--- end output ---"
  exit 1
fi

# ── assertions ───────────────────────────────────────────────────────────────
if [ ! -f .mock-update-prompt ] || ! grep -q -- "--base $base_head" .mock-update-prompt; then
  echo "FAIL: stale-context recovery did not use manifest.sourceCommit for edc-update"
  echo "--- update prompt ---"
  cat .mock-update-prompt 2>/dev/null || true
  echo "--- end update prompt ---"
  exit 1
fi
echo "PASS: stale-context recovery uses manifest.sourceCommit for edc-update"

final=$(ls review-*.md 2>/dev/null | head -1 || true)
if [ -z "$final" ]; then
  echo "FAIL: no review-*.md final file produced"
  echo "--- output ---"
  echo "$out"
  echo "--- end output ---"
  exit 1
fi
echo "PASS: final review file produced ($final)"

if ! grep -q '^##' "$final"; then
  echo "FAIL: final file $final has no '##' heading (consolidate didn't merge module reports)"
  exit 1
fi
echo "PASS: final review file has ## headings"

# Per-module IPC belongs under git-private run storage, never edc-context/.
max_overlap=$(sort -nr "$TMPDIR_T6/.git/probe/overlap" 2>/dev/null | head -1 || echo 0)
staged_reports=0
if [ -d .git/edc/runs ]; then
  staged_reports=$(find .git/edc/runs -path '*/staged/review-tasks/report-*.md' -type f | wc -l | tr -d ' ')
fi
if [ "$max_overlap" -ne 2 ] || [ "$staged_reports" -ne 2 ]; then
  echo "FAIL: expected two overlapping staged review workers (overlap=$max_overlap reports=$staged_reports)"
  echo "$out"
  exit 1
fi
echo "PASS: security workers overlap at configured bound"

if [ -d edc-context/review-tasks ]; then
  echo "FAIL: security IPC leaked into edc-context/review-tasks"
  exit 1
fi

echo "PASS: security task scaffolding stays in git-private run storage"

echo ""
echo "All T6 checks passed."
