#!/usr/bin/env bash
# Task 6 smoke test: end-to-end auto_mode pipeline with a mocked agent CLI.
#
# Catches regressions where the orchestrator can no longer spawn its agent
# subprocesses — the canonical example being the run_with_timeout-cannot-exec-
# shell-functions bug (see commit history around the run_agent removal).
#
# Strategy:
#   1. Build a fake "claude" binary on PATH that reads a prompt from stdin and
#      writes whatever artifact the orchestrator expects for that phase.
#   2. Set up a minimal git repo with pre-existing valid context.
#   3. Make a one-file "change" and run `edc-review.sh HEAD --base HEAD~1`.
#   4. Assert the stale-context recovery preserves `--base HEAD~1`.
#   5. Assert a final review-*.md file is produced.
#
# Run from repo root: bash tests/hardening/t6-auto-mode.sh
set -euo pipefail

SCRIPT_REL="plugins/edc/scripts/edc-review.sh"
ORIG_DIR="$(pwd)"
SCRIPT="$ORIG_DIR/$SCRIPT_REL"
TMPDIR_T6=$(mktemp -d)
MOCK_BIN="$TMPDIR_T6/bin"
trap 'rm -rf "$TMPDIR_T6"' EXIT

echo "=== T6: end-to-end auto_mode pipeline (mocked agent) ==="

# ── build the mock agent ─────────────────────────────────────────────────────
mkdir -p "$MOCK_BIN"
cat > "$MOCK_BIN/claude" <<'MOCK'
#!/usr/bin/env bash
# Mock claude CLI for t6. Reads the prompt from stdin (here-string from the
# orchestrator) and writes the artifact the orchestrator expects for that phase.
#
# Recognized phases:
#   - prompt mentions "edc-build" → write valid .context/{context.md,.meta.json}
#   - prompt mentions "edc-update" → refresh .meta.json:lastCommit to HEAD
#   - prompt mentions "--task-file <path>" → write report-<module>.md with ## heading
#
# Always exits 0 with empty stdout (stream_filter handles empty input fine).
set -euo pipefail
prompt=$(cat)

if [[ "$prompt" == *"edc-build"* ]]; then
  mkdir -p .context
  printf '<!-- generated by t6 mock -->\n# Stub Architecture\n\n## Module Map\n\n- root\n' > .context/context.md
  head=$(git rev-parse HEAD)
  printf '{"lastCommit":"%s","modules":{"root":{"files":["change.txt"],"contextFile":".context/root.md"}}}\n' "$head" > .context/.meta.json
  printf '<!-- generated by t6 mock -->\n# root\n\n## Files\n\n- change.txt\n' > .context/root.md
  exit 0
fi

if [[ "$prompt" == *"edc-update"* ]]; then
  printf '%s' "$prompt" > .mock-update-prompt
  head=$(git rev-parse HEAD)
  # Naive in-place rewrite of lastCommit. Adequate for test purposes.
  sed -i.bak 's/"lastCommit":"[^"]*"/"lastCommit":"'"$head"'"/' .context/.meta.json
  rm -f .context/.meta.json.bak
  exit 0
fi

if [[ "$prompt" == *"--task-file"* ]]; then
  task_path=$(printf '%s' "$prompt" | grep -oE -- '--task-file [^ ]+' | head -1 | awk '{print $2}')
  if [ -z "$task_path" ]; then
    echo "MOCK ERROR: could not parse --task-file from prompt" >&2
    exit 1
  fi
  module=$(basename "$task_path" .md)
  mkdir -p review-tasks
  printf '## Summary\n\nMock review for module %s.\n' "$module" > "review-tasks/report-${module}.md"
  exit 0
fi

echo "MOCK ERROR: unrecognized prompt: $prompt" >&2
exit 1
MOCK
chmod +x "$MOCK_BIN/claude"

# ── set up a minimal git repo with valid pre-existing context ────────────────
cd "$TMPDIR_T6"
# Insulate from any host git config (gpg signing, hooks, etc.) that would
# otherwise make `git commit` block or fail. GIT_CONFIG_GLOBAL=/dev/null gives
# us a hermetic per-test git environment.
export GIT_CONFIG_GLOBAL=/dev/null
export GIT_CONFIG_SYSTEM=/dev/null
git init -q
git config user.email "test@test.com"
git config user.name "Test"
git config commit.gpgsign false
echo "initial" > seed.txt
git add seed.txt
git commit -q -m "init"

# Pre-populate valid context (already-fresh: lastCommit == HEAD-of-base, but we
# add another commit below and rely on auto_mode's CONTEXT_STALE → edc-update
# recovery to bring it forward). This is the realistic happy path.
mkdir -p .context
base_head=$(git rev-parse HEAD)
printf '<!-- generated by t6 -->\n# Stub Architecture\n\n## Module Map\n\n- root\n' > .context/context.md
printf '{"lastCommit":"%s","modules":{"root":{"files":["change.txt"],"contextFile":".context/root.md"}}}\n' "$base_head" > .context/.meta.json
printf '<!-- generated by t6 -->\n# root\n\n## Files\n\n- change.txt\n' > .context/root.md

# Make a real change so build_mode finds a diff to review.
echo "modified" > change.txt
git add change.txt
git commit -q -m "add change"

# ── run the orchestrator with mocked claude on PATH ──────────────────────────
export PATH="$MOCK_BIN:$PATH"
export EDC_AGENT_CLI=claude

# Sanity: the mock is what gets resolved.
which_claude=$(command -v claude)
if [ "$which_claude" != "$MOCK_BIN/claude" ]; then
  echo "FAIL: mock claude not first on PATH (got $which_claude)"
  exit 1
fi
echo "→ using mock claude at: $which_claude"

# Run the full pipeline. Use an explicit --base so the stale-context recovery
# path must preserve it when spawning edc-update. Capture output for diagnostics.
result=0
out=$(bash "$SCRIPT" HEAD --base HEAD~1 2>&1) || result=$?

if [ "$result" -ne 0 ]; then
  echo "FAIL: orchestrator exited non-zero ($result)"
  echo "--- output ---"
  echo "$out"
  echo "--- end output ---"
  exit 1
fi

# ── assertions ───────────────────────────────────────────────────────────────
if [ ! -f .mock-update-prompt ] || ! grep -q -- '--base HEAD~1' .mock-update-prompt; then
  echo "FAIL: stale-context recovery did not preserve --base HEAD~1 for edc-update"
  echo "--- update prompt ---"
  cat .mock-update-prompt 2>/dev/null || true
  echo "--- end update prompt ---"
  exit 1
fi
echo "PASS: stale-context recovery preserves --base for edc-update"

final=$(ls review-*.md 2>/dev/null | head -1 || true)
if [ -z "$final" ]; then
  echo "FAIL: no review-*.md final file produced"
  echo "--- output ---"
  echo "$out"
  echo "--- end output ---"
  exit 1
fi
echo "PASS: final review file produced ($final)"

if ! grep -q '^##' "$final"; then
  echo "FAIL: final file $final has no '##' heading (consolidate didn't merge module reports)"
  exit 1
fi
echo "PASS: final review file has ## headings"

if ! ls review-tasks/report-*.md > /dev/null 2>&1; then
  echo "FAIL: no per-module reports left under review-tasks/"
  exit 1
fi
echo "PASS: per-module reports present"

echo ""
echo "All T6 checks passed."
