#!/usr/bin/env bash
# Task 7 smoke test: end-to-end auto_mode pipeline with mocked `codex exec`.
#
# Verifies the Codex path can:
#   1. resolve project-local .codex skills for prompt construction
#   2. spawn `codex exec` in auto_mode
#   3. recover stale context via edc-update from manifest.sourceCommit
#   4. produce the final consolidated review file
#
# Run from repo root: bash tests/hardening/t7-codex-auto-mode.sh
set -euo pipefail


SCRIPT_REL="plugins/edc/scripts/edc-review.sh"
ORIG_DIR="$(pwd)"
SCRIPT="$ORIG_DIR/$SCRIPT_REL"
TMPDIR_T7=$(mktemp -d)
MOCK_BIN="$TMPDIR_T7/bin"
trap 'rm -rf "$TMPDIR_T7"' EXIT

echo "=== T7: end-to-end auto_mode pipeline (mocked codex) ==="

mkdir -p "$MOCK_BIN"
cat > "$MOCK_BIN/codex" <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail

subcommand="${1:-}"
if [ "$subcommand" != "exec" ]; then
  echo "MOCK ERROR: expected 'exec' subcommand, got: $subcommand" >&2
  exit 1
fi

# Pin the orchestrator→codex flag contract. Drop or rename any of these and
# this mock trips immediately, so t7 fails before the stream would silently
# regress.
all_args="$*"
for required in "--json" "--color never" "--sandbox workspace-write"; do
  if [[ "$all_args" != *"$required"* ]]; then
    echo "MOCK ERROR: expected flag '$required' in: $all_args" >&2
    exit 1
  fi
done
# Prompt must be piped on stdin (orchestrator uses `-` sentinel + here-string).
if [[ "$all_args" != *" -"* && "$all_args" != *"-"* ]]; then
  echo "MOCK ERROR: expected '-' stdin sentinel in: $all_args" >&2
  exit 1
fi

prompt=$(cat)
if [ -z "$prompt" ]; then
  echo "MOCK ERROR: empty prompt on stdin" >&2
  exit 1
fi

# Review prompts are structured: "TASK FILE: <path>" header line. Check this
# before build/update markers because the embedded review methodology mentions
# update/build concepts.
if [[ "$prompt" == *"TASK FILE: "* ]]; then
  task_path=$(printf '%s' "$prompt" | grep -oE 'TASK FILE: [^ ]+' | head -1 | awk '{print $3}')
  if [ -z "$task_path" ]; then
    echo "MOCK ERROR: could not parse TASK FILE from prompt" >&2
    exit 1
  fi
  module=$(basename "$task_path" .md)
  task_dir=$(dirname "$task_path")
  mkdir -p "$task_dir"
  printf '## Findings\n\nMock review for module %s.\n' "$module" > "$task_dir/report-${module}.md"
  exit 0
fi

# Test fixtures stub each skill with a one-line marker. Check update before
# build because the real update prompt can mention build recovery paths.
if [[ "$prompt" == *"edc-update"* ]]; then
  printf '%s' "$prompt" > .mock-update-prompt
  head=$(git rev-parse HEAD)
  sed -i.bak 's/"sourceCommit":"[^"]*"/"sourceCommit":"'"$head"'"/' edc-context/manifest.json
  rm -f edc-context/manifest.json.bak
  exit 0
fi

if [[ "$prompt" == *"edc-build"* ]]; then
  mkdir -p edc-context/modules
  printf '<!-- generated by t7 mock -->\n# Stub Architecture\n\n## Module Map\n\n- root\n' > edc-context/index.md
  head=$(git rev-parse HEAD)
  printf '{"schemaVersion":2,"sourceCommit":"%s","modules":[{"name":"root","doc":"edc-context/modules/root.md"}]}\n' "$head" > edc-context/manifest.json
  printf '<!-- generated by t7 mock -->\n# root\n\n## Files\n\n- change.txt\n' > edc-context/modules/root.md
  exit 0
fi

echo "MOCK ERROR: unrecognized prompt: $prompt" >&2
exit 1
MOCK
chmod +x "$MOCK_BIN/codex"

cd "$TMPDIR_T7"
export GIT_CONFIG_GLOBAL=/dev/null
export GIT_CONFIG_SYSTEM=/dev/null
git init -q
git config user.email "test@test.com"
git config user.name "Test"
git config commit.gpgsign false
echo "initial" > seed.txt
git add seed.txt
git commit -q -m "init"

mkdir -p .edc/skills/edc-build-impl
mkdir -p .edc/skills/edc-update-impl
mkdir -p .edc/skills/edc-review
printf 'edc-build\n' > .edc/skills/edc-build-impl/SKILL.md
printf 'edc-update\n' > .edc/skills/edc-update-impl/SKILL.md
printf 'edc-review\n' > .edc/skills/edc-review/SKILL.md
printf '# methodology\n' > .edc/skills/edc-review/methodology.md
printf '# adversarial\n' > .edc/skills/edc-review/adversarial.md
printf '# reporting\n' > .edc/skills/edc-review/reporting.md
printf '# patterns\n' > .edc/skills/edc-review/patterns.md

mkdir -p edc-context/modules
base_head=$(git rev-parse HEAD)
printf '<!-- generated by t7 -->\n# Stub Architecture\n\n## Module Map\n\n- root\n' > edc-context/index.md
printf '{"schemaVersion":2,"sourceCommit":"%s","modules":[{"name":"root","doc":"edc-context/modules/root.md"}]}\n' "$base_head" > edc-context/manifest.json
printf '<!-- generated by t7 -->\n# root\n\n## Files\n\n- change.txt\n' > edc-context/modules/root.md

echo "modified" > change.txt
git add change.txt
git commit -q -m "add change"

export PATH="$MOCK_BIN:$PATH"
export EDC_AGENT_CLI=codex
export EDC_CODEX_HOME="$TMPDIR_T7/codex-home"

which_codex=$(command -v codex)
if [ "$which_codex" != "$MOCK_BIN/codex" ]; then
  echo "FAIL: mock codex not first on PATH (got $which_codex)"
  exit 1
fi
echo "→ using mock codex at: $which_codex"

result=0
out=$(bash "$SCRIPT" HEAD --base HEAD~1 2>&1) || result=$?

if [ "$result" -ne 0 ]; then
  echo "FAIL: orchestrator exited non-zero ($result)"
  echo "--- output ---"
  echo "$out"
  echo "--- end output ---"
  exit 1
fi

if [ ! -f .mock-update-prompt ] || ! grep -q -- "--base $base_head" .mock-update-prompt; then
  echo "FAIL: stale-context recovery did not use manifest.sourceCommit for codex edc-update"
  echo "--- update prompt ---"
  cat .mock-update-prompt 2>/dev/null || true
  echo "--- end update prompt ---"
  exit 1
fi
echo "PASS: stale-context recovery uses manifest.sourceCommit for codex edc-update"

final=$(ls review-*.md 2>/dev/null | head -1 || true)
if [ -z "$final" ]; then
  echo "FAIL: no review-*.md final file produced"
  echo "--- output ---"
  echo "$out"
  echo "--- end output ---"
  exit 1
fi
echo "PASS: final review file produced ($final)"

if ! grep -q '^##' "$final"; then
  echo "FAIL: final file $final has no '##' heading"
  exit 1
fi
echo "PASS: final review file has ## headings"

# Per-module reports under edc-context/review-tasks/ are IPC scaffolding;
# auto_mode removes them on success. Assert the cleanup happened.
if [ -d edc-context/review-tasks ]; then
  echo "FAIL: edc-context/review-tasks/ not cleaned up after successful run"
  ls edc-context/review-tasks/
  exit 1
fi
echo "PASS: review-tasks scaffold cleaned up on success"

echo ""
echo "All T7 checks passed."
