export const SUBPROCESS_TERMINATION_GRACE_MS = 1000;
export const WORKER_PROCESS_GROUP_TERMINATION_GRACE_MS = SUBPROCESS_TERMINATION_GRACE_MS;
export const BACKGROUND_JOB_SUPERVISOR_MARGIN_MS = 1000;
// Keep bootstrap alive through worker-pool cleanup, then give its outer Pi
// supervisor another full margin before escalation.
export const RUNTIME_BOOTSTRAP_TERMINATION_GRACE_MS =
  WORKER_PROCESS_GROUP_TERMINATION_GRACE_MS + BACKGROUND_JOB_SUPERVISOR_MARGIN_MS;
export const BACKGROUND_JOB_TERMINATION_GRACE_MS =
  RUNTIME_BOOTSTRAP_TERMINATION_GRACE_MS + BACKGROUND_JOB_SUPERVISOR_MARGIN_MS;
